### ISSUE TITLE
mcMMO userdata clearing

### ISSUE THREAD

**Issue by Theepwner** [mcMMO-Dev/mcMMO#2281] opened 2014-09-09 04:14 UTC
Hello,

I am using mcMMO #3682 and it loads user data perfectly after the first time the server loads, but when the server stops/restarts, then all of the data is cleared.  The data that I was trying to convert was data from almost a month ago.  I really hope you guys can fix this.

**Comment by TfT-02** [comment] 2015-01-10 11:37
This ticket is a duplicate of https://github.com/mcMMO-Dev/mcMMO/issues/2225, please refer to that ticket and post your findings or questions on there. We're aware of this issue and are working on a fix.

**Closed by TfT-02** 2015-01-10 11:37 UTC
Labels: Confirmed Bug, Duplicate
