### ISSUE TITLE
Not Enabling #2927

### ISSUE THREAD

**Issue by ghost** [mcMMO-Dev/mcMMO#2928] opened 2016-05-07 19:20 UTC
Since you closed the issue when the issue was not resolved 

https://github.com/mcMMO-Dev/mcMMO/issues/2927

As stated the treasures.yml file was never touched the only thing changed was me putting in the sql details in the config file.

**Comment by t00thpick1** [comment] 2016-05-08 14:57
Try regenerating your config on the 1.7 build, if that does not work, post your treasures.yml here so I can see it.

**Comment by Stuart74** [comment] 2016-05-08 15:26
Regenerated the config as asked still not enabling 

My treasures.yml file

http://pastebin.com/pNZS2zAD

**Comment by t00thpick1** [comment] 2016-05-10 02:31
"Last updated on 1.5.05-SNAPSHOT-b136"  That config was generated on the latest 1.9 build, it won't run on the older versions,  regenerate the configw hile running the 1.7 build...

**Comment by Stuart74** [comment] 2016-05-10 11:23
Still not enabling 

console err http://pastebin.com/ki7BQ7de  

Regenerated treasures.yml file -- http://pastebin.com/2by0rwUp

Regenerated Config.yml file - http://pastebin.com/QxDUrSHg

**Comment by t00thpick1** [comment] 2016-05-10 13:58
Looks like its your repair config now.

**Comment by Stuart74** [comment] 2016-05-10 14:26
Repair.yml    http://pastebin.com/PJ3jA9mC

**Comment by Stuart74** [comment] 2016-05-13 03:23
Is there a fix for this yet ??

**Comment by t00thpick1** [comment] 2016-05-15 03:51
Sorry, can I see the errors with the current configs?(The ones you regenerated for me)

**Comment by Stuart74** [comment] 2016-05-15 13:02
Error is below 

http://pastebin.com/d8xXJurs

I understand your busy but this has been an issue over a week now its getting to the point that i rather not use it even though i paid for it . Seems its not an isolated issue this is a problem i seem to have seen a lot of people having in regards to mcmmo. Its a shame i used it back in the old days with no issue.

**Comment by t00thpick1** [comment] 2016-05-19 01:37
I'm honestly not sure what the issue is here, I'm not familiar enough with modded 1.7 servers to understand the relevant part of stack trace there.

**Comment by alphademic** [comment] 2016-06-09 17:04
Also having a NullPointerException.  Running from Thermos 1.7.10 (1614.57)

[Here is my pastebin of the error from the server log.](http://pastebin.com/k8JRuKne)

**Closed** 2018-07-24 23:57 UTC
