### ISSUE TITLE
Ore dupe bug with pistons and slime blocks with mining double drop.

### ISSUE THREAD

**Issue by mibby** [mcMMO-Dev/mcMMO#2419] opened 2015-01-19 18:09 UTC
Moved to https://trello.com/c/QtelmXlx (dev only)

**Comment by TfT-02** [comment] 2015-02-09 08:29
Apologies for the late response, if this bug is back - we need to handle it asap.

**Comment by mibby** [comment] 2015-02-09 08:33
Great. I'll be here to test whenever an attempt to fix it is made.

**Comment by ulumulu1510** [comment] 2015-02-11 11:19
This bug is back, I can confirm it for the version that I compiled when pulling it from github yesterday.

Our server made a bug-report for our main Tech-administrator that can be viewed here:
https://docs.google.com/document/d/1r5NVBfvAo8dZFhYEWuFxjFdiqzqbXxeOUhoFIfr5LYY/edit#

I hope it is of help for you  and we can get the bug fixed as asoon as possible.

**Comment by ulumulu1510** [comment] 2015-02-11 19:14
I think I actually might have found the bug:

https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/java/com/gmail/nossr50/runnables/StickyPistonTrackerTask.java#L34

 This line should be:
mcMMO.getPlaceStore().setTrue(movedBlock.getRelative(direction));

Instead of:
mcMMO.getPlaceStore().setTrue(block.getRelative(direction));

**Comment by MorroZ** [comment] 2015-02-16 14:23
any changes yet?

**Comment by ulumulu1510** [comment] 2015-02-16 18:23
@MorroZ , the PR has been pulled. In a next version, it will be fixed I assume.

**Comment by k3ldon** [comment] 2015-02-23 21:31
still works...

**Comment by TfT-02** [comment] 2015-02-25 20:29
@k3ldon Version number?

**Comment by MorroZ** [comment] 2015-02-25 21:14
@TfT-02 w8 is there already a version where this bug is fixed? where can i find it?^^

**Comment by k3ldon** [comment] 2015-02-25 21:36
latest... I actually update for that reason
[mcMMO] Loading mcMMO v1.5.02-SNAPSHOT-b${BUILD_NUMBER}

**Comment by Absentee23** [comment] 2015-02-26 01:09
Can confirm, using build 33, the dupe still works.

**Comment by TfT-02** [comment] 2015-02-28 14:24
@Absentee23 With which Spigot build?

I've just tried to reproduce this bug and was not able to on git-Spigot-c3c767f-33d5de3 and mcMMO v1.5.02-SNAPSHOT-b34

**Comment by MorroZ** [comment] 2015-03-01 14:14
@TfT-02 

[15:12:18 INFO]: This server is running CraftBukkit version git-Spigot-c3c767f-33d5de3 (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)
[15:12:18 INFO]: You are running the latest version

[15:13:12 INFO]: [mcMMO] Running version 1.5.02-SNAPSHOT-b34

The dupe still works for me too, with this http://prntscr.com/6bc1yn

:/

**Comment by MorroZ** [comment] 2015-03-01 14:54
@TfT-02 i think i found the problem?

if u push ores with normal pistons the duping process cant be reproduced this is fixed, but with sticky pistons its still possible.

**Comment by k3ldon** [comment] 2015-03-01 18:21
look

https://www.youtube.com/watch?v=w1QFUq_M0nU&feature=youtu.be

**Comment by jessefjxm** [comment] 2015-03-04 01:51
Bug still works on #035

**Comment by TfT-02** [comment] 2015-03-21 15:18
Was able to reproduce this bug. Trying to figure out where the tracking is going wrong with these pistons.

**Comment by TfT-02** [comment] 2015-03-21 18:25
Fixed

**Closed by TfT-02** 2015-03-21 18:25 UTC
Labels: Confirmed Bug, Fixed
