### ISSUE TITLE
"A plugin is creating a recipe using a Deprecated method." warning during server startup

### ISSUE THREAD

**Issue by benkillin** [mcMMO-Dev/mcMMO#3434] opened 2018-04-26 01:08 UTC
```
[22:58:34 INFO]: Default game type: SURVIVAL
[22:58:34 INFO]: This server is running Paper version git-TacoSpigot-"8014601" (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[22:58:34 INFO]: Server Ping Player Sample Count: 12
[22:58:34 INFO]: Using 4 threads for Netty based IO
[22:58:34 INFO]: Debug logging is disabled
[22:58:34 INFO]: Generating keypair
[22:58:35 INFO]: Starting Minecraft server on *:4001
[22:58:35 INFO]: Using epoll channel type
[22:58:35 INFO]: Set PluginClassLoader as parallel capable
[22:58:35 INFO]: [mcMMO] Loading mcMMO v1.5.09-SNAPSHOT
[22:58:35 INFO]: [Vault] Loading Vault v1.5.6-b49
[22:58:35 INFO]: [Essentials] Loading Essentials v2.15.0.613
[22:58:35 INFO]: [EssentialsProtect] Loading EssentialsProtect v2.15.0.613
[22:58:35 INFO]: [UltraPermissions] Loading UltraPermissions v2.0.7
[22:58:35 INFO]: [EssentialsSpawn] Loading EssentialsSpawn v2.15.0.613
[22:58:35 INFO]: [ZHorse] Loading ZHorse v1.6.9
[22:58:35 INFO]: [EssentialsChat] Loading EssentialsChat v2.15.0.613
[22:58:35 INFO]: [ProtocolLib] Loading ProtocolLib v4.4.0-SNAPSHOT-b390
[22:58:35 INFO]: [EssentialsAntiBuild] Loading EssentialsAntiBuild v2.15.0.613
[22:58:35 INFO]: [PlayerVaults] Loading PlayerVaults v4.0.5
[22:58:35 INFO]: [mcMMOAction] Loading mcMMOAction v2.3.2
[22:58:35 INFO]: Server permissions file permissions.yml is empty, ignoring it
[22:58:35 INFO]: [mcMMO] Enabling mcMMO v1.5.09-SNAPSHOT
[22:58:36 WARN]: java.lang.Throwable: Warning: A plugin is creating a recipe using a Deprecated method. This will cause you to receive warnings stating 'Tried to load unrecognized recipe: bukkit:<ID>'. Please ask the author to give their recipe a static key using NamespacedKey.
[22:58:36 WARN]:        at org.bukkit.inventory.ShapelessRecipe.<init>(ShapelessRecipe.java:26)
[22:58:36 WARN]:        at com.gmail.nossr50.util.ChimaeraWing.getChimaeraWingRecipe(ChimaeraWing.java:164)
[22:58:36 WARN]:        at com.gmail.nossr50.mcMMO.registerCustomRecipes(mcMMO.java:437)
[22:58:36 WARN]:        at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:167)
[22:58:36 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[22:58:36 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[22:58:36 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[22:58:36 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:387)
[22:58:36 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:336)
[22:58:36 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:226)
[22:58:36 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[22:58:36 WARN]:        at java.lang.Thread.run(Thread.java:748)
[22:58:37 INFO]: [Vault] Enabling Vault v1.5.6-b49
[22:58:37 INFO]: [Vault] [Economy] Essentials Economy found: Waiting
[22:58:37 INFO]: [Vault] [Permission] SuperPermissions loaded as backup permission system.
[22:58:37 INFO]: [Vault] Enabled Version 1.5.6-b49
[22:58:37 INFO]: [ProtocolLib] Enabling ProtocolLib v4.4.0-SNAPSHOT-b390
[22:58:37 INFO]: [ProtocolLib] Started structure compiler thread.
```

**Comment by Glitchfinder** [comment] 2018-04-26 05:34
Duplicate of #3358, #3411, and #3416. It's been addressed, will not currently cause problems, and will be completely gone in the next build uploaded to Spigot.

**Closed by Glitchfinder** 2018-04-26 05:34 UTC
Labels: Confirmed Bug, Duplicate, Fixed
