### ISSUE TITLE
UUIDs not converting properly

### ISSUE THREAD

**Issue by Gnarusly** [mcMMO-Dev/mcMMO#2382] opened 2014-12-20 12:06 UTC
When I try to update to a version of mcMMO that uses UUIDs, it does not work. I have locked down the server so no one can join and this has not helped.

![updating uuids](https://cloud.githubusercontent.com/assets/5558792/5514729/4ac9bbf2-889c-11e4-8fc3-d6e5592a3c8e.png)
This is the screenshot of what happens when I start the server with the UUID-compatible build of mcMMO, currently using the 1.5.01-SNAPSHOT.

This is the leaderboards BEFORE the UUID conversion:
![leaderboards before](https://cloud.githubusercontent.com/assets/5558792/5514730/67a591ec-889c-11e4-87eb-3ab03866335a.png)

And this is the leaderboards AFTER the UUID conversion:
![leaderboards after](https://cloud.githubusercontent.com/assets/5558792/5514731/6d856056-889c-11e4-8171-bc892cd1e818.png)

 This server is running CraftBukkit version git-Spigot-8dc4297-adc129a (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)

mcMMO version: 1.5.01-b8

There are no errors in the log.

I have performed this using an online-mode server. I have also tested this with an offline mode server, and it did not help.

I am using flatfile. I have tried converting to SQL and trying this whole process again, and it did not help.

**Comment by TfT-02** [comment] 2015-01-10 11:38
This ticket is a duplicate of https://github.com/mcMMO-Dev/mcMMO/issues/2225, please refer to that ticket and post your findings or questions on there. We're aware of this issue and are working on a fix.

**Closed by TfT-02** 2015-01-10 11:38 UTC
Labels: Confirmed Bug
