### ISSUE TITLE
Repair Skill

### ISSUE THREAD

**Issue by Retrinity** [mcMMO-Dev/mcMMO#2396] opened 2015-01-01 18:05 UTC
When you try to repair armor with an anvil (Iron Block) you, it will put your armor on so you can't repair it multiple times. You have to take it off every single time you want to repair it a little

**Comment by TfT-02** [comment] 2015-01-01 19:46
Confirmed on `git-Spigot-eb39b47-0899683 (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)`, though I believe this is not a bug on mcMMO's side.
mcMMO is canceling the interact event, but Spigot is not checking it when equipping the armor.

**Comment by TfT-02** [comment] 2015-02-28 15:26
Fixed on Spigot's side.

**Closed by TfT-02** 2015-02-28 15:26 UTC
