### ISSUE TITLE
Super breaker deletes Efficiency enchantment from pickaxes

### ISSUE THREAD

**Issue by translayton** [mcMMO-Dev/mcMMO#2460] opened 2015-02-15 22:42 UTC
Any enchanted pickaxes, after players activate Super Breaker ability, loses the efficiency enchantment and leaves only the other enchants. How can I fix this?
I use mcMMO 1.5.00

**Comment by tomibizjak123** [comment] 2015-03-03 15:09
You can't. Not your fault.

**Comment by TfT-02** [comment] 2015-04-10 15:50
I was not able to reproduce this bug on mcMMO v1.5.03-SNAPSHOT-b46, please try updating mcMMO to the latest dev build and report back if the problem is solved or still persist.

**Comment by SirWilli** [comment] 2015-07-02 23:38
I have the same bug in 1.5.00-b3547

**Comment by EvilOlaf** [comment] 2015-07-03 05:26
Not reproducible in 1.5.03-SNAPSHOT.

**Comment by SirWilli** [comment] 2015-07-03 17:44
I can't use 1.5.03-SNAPSHOT as it is for 1.8

**Comment by tincopper2** [comment] 2015-09-29 03:53
I have the bug in 1.5.00-b3547

**Comment by EvilOlaf** [comment] 2015-09-29 08:30
I am not sure but maybe it is backwards compatible. Just give it a try.

**Comment by tincopper2** [comment] 2015-09-30 21:38
Do you mean try a version intended for 1.8 on 1.7.10?

**Comment by tincopper2** [comment] 2015-09-30 21:57
I tried with the latest version on github and it still doesnt work

**Comment by Jackatz** [comment] 2016-12-12 05:08
happened to me as well

**Comment by Jackatz** [comment] 2016-12-12 05:08
Does anyone know a fix for this bug? im running latest 1.7.10 verison

**Comment by EvilOlaf** [comment] 2016-12-12 07:07
AFAIK mcmmo is currently not backwards compatible. So try to use an older build if you find one (like on dev bukkit). Though there will be no support if you run into issues.

**Comment by tincopper2** [comment] 2016-12-12 23:57
I looked into the source code a while back and was able to fix this bug through some modification, but that was around when this bug was posted on a broken hard drive.

**Closed** 2018-12-28 14:32 UTC
Labels: Unconfirmed Bug, Waiting for Response
