### ISSUE TITLE
There was an error while enabling mcMMO! "java.lang.IllegalStateException: Queue full"

### ISSUE THREAD

**Issue by cloakfox** [mcMMO-Dev/mcMMO#4711] opened 2022-01-06 10:33 UTC
Mcmmo fails to load on our paper 1.18.1 server
https://gist.github.com/cloakfox/3ac073d3ae849cf624927281663573e5

git-Paper-130 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: eb98398)

**Comment by Geolykt** [comment] 2022-01-06 10:34
Duplicate of #4702

**Comment by CheesyTheArtist** [comment] 2022-01-06 14:11
Fixed on paper build 134, upgrade to that build please.

**Closed** 2022-01-06 17:01 UTC
