### ISSUE TITLE
alchemy experience

### ISSUE THREAD

**Issue by Ahkara** [mcMMO-Dev/mcMMO#3564] opened 2018-09-08 06:30 UTC
The server is 1.13.
The experience of alchemy is not up.
I checked all the settings.
NETHER_WART was modified to NETHER_STALK.
Give me a hand.

**Comment by Ahkara** [comment] 2018-09-08 06:41
[advenced.txt](https://github.com/mcMMO-Dev/mcMMO/files/2363090/advenced.txt)
[potions.txt](https://github.com/mcMMO-Dev/mcMMO/files/2363091/potions.txt)

**Comment by Zappa2510** [comment] 2018-09-13 17:00
for me the issue is limited to new players. alchemy works for older players and as well party sharing xp with new players.

**Comment by Momshroom** [comment] 2018-09-15 00:39
For me it's completely random... sometimes you get mcmmo xp.. sometimes you don't... I've had players chart when they do and when they don't and exactly how they're putting items in... there doesn't seem to be a pattern.

**Comment by t00thpick1** [comment] 2018-09-15 00:55
@Momshroom Hmm interesting, I've been trying to reproduce this locally and having trouble, if you can help narrow that down it would be swell.

**Comment by t00thpick1** [comment] 2018-09-15 02:53
@Momshroom Just to be 100% sure, some ingredients(specifically pufferfish and the ghostly_membrane and turtle thing) were not updated in the config until now, were they the ones that didn't give xp?

**Comment by Sikatsu** [comment] 2018-09-15 03:38
@t00thpick1 Some default configs still need to be updated in general, like fishing doesn't work yet with the new shells and even in experience/treasure configs old names are used. I think this was the same for alchemy.

**Comment by t00thpick1** [comment] 2018-09-15 03:41
@Sikatsu Yeah I've been working on that today, Just got all the herbalism perms fixed, and remade the entire potions config.

**Comment by Sikatsu** [comment] 2018-09-15 03:43
Yep great work on that! I'll do some testings later today.

**Comment by Momshroom** [comment] 2018-09-15 05:54
No it wasn't just pufferfish, etc.  

And after testing further, I'm even more confused... on my test server, we get experience most, but not all the time.  On my production server we only rarely get experience, even for making awkward potions and speed and other very basic potions. 

They have almost exactly the same plugins, and nearly identical configurations. (The production server has the enjin plugin and serverlistplus as the only additions, neither seems a likely interference.)

**Comment by Sikatsu** [comment] 2018-09-15 08:45
Alchemy still levels really slow.

**Comment by Glitchfinder** [comment] 2018-09-15 16:38
I agree, though that's more an issue with the default configuration than it is with the skill itself. The skill uses the same experience curve as everything else, and the experience granted by using it is similar to other skills. However, unlike most other skills, you can't just do a few hundred experience earning actions in a few minutes. Reasonably, it would be wise to boost the default alchemy experience by a factor of ten or so.

**Comment by Momshroom** [comment] 2018-09-15 17:52
It’s not simply that.  It’s that many times, actions that should give xp do
not.

**Comment by Glitchfinder** [comment] 2018-09-15 18:42
Even with 100% of alchemy experience granted, the base levels for experience are so low that the skill is incredibly slow to level compared to other skills in mcMMO. I am aware that alchemy isn't granting all experience it should be at the moment, but the comparatively low experience levels are an issue it's had since it was first incorporated into the plugin.

**Comment by thunderlight411** [comment] 2018-10-02 10:49
Still no experiance recieved when making a potion.
Have tried all the required ingredients but nothing works.
Users have mcmmo.default as permission.
even with * en OP there is no experience recived when making any potions.

i have created a new server with new files generated for mcmmo.
but nothing changed.
Is there any information how or when this is going to be fixt ?

**Comment by Zappa2510** [comment] 2018-10-02 14:57
it does work for older data files from 1.12, but newer data for players made after 1.13 is still iffy. its like you said some times you get xp and sometimes nothing. really seems odd to how this is. hopefully it can be fixed soon.

**Comment by Quavelen** [comment] 2018-11-03 08:33
@t00thpick1 I'd like to mention that this is still occuring, on the latest Mcmmo dev build (51) on Spigot 1.13.2. Freshly downloaded mcmmo.jar and generated config files, and not a single stage of fire resistance potions give experience. Here's a short video I recorded for you, showing each stage, and then showing that experience gain from other things (crops was the example) is working: https://www.youtube.com/watch?v=neyTcKwype4


Is there any progress on this, or have you still been unable to reproduce it? =/

**Comment by aegisjester** [comment] 2018-11-27 02:00
Following up with this.

If this gets fixed by the end of the week, I will donate $200

**Closed** 2018-11-27 04:11 UTC

**Comment by aegisjester** [comment] 2018-11-27 05:03
Thanks. Initial testing looks promising, I'll follow up with others in the next day to verify

**Comment by Quavelen** [comment] 2018-11-27 13:34
It works! Thank you so much, @t00thpick1, =)
