### ISSUE TITLE
1.12.1 version cannot use hopper in nether

### ISSUE THREAD

**Issue by NyanMeow** [mcMMO-Dev/mcMMO#3257] opened 2017-08-11 12:43 UTC
Hello！

I uninstalled the mcMMO server after found that the nether cannot use hopper's BUG is fixed, because my nether is the EpicNetherGenerator plugin control, that is not caused by EpicNetherGenerator plugin, the result is mcMMO in the hope to repair the BUG, thanks again!

**Comment by AllPlayed** [comment] 2017-08-15 13:05
Hello
This will be fixed with the new 1.12.1 version of MCMMO, just be patient 🙂

**Comment by ezeiger92** [comment] 2017-08-15 21:27
Be skeptical of @AllPlayed, I have not seen a single piece of evidence that he has any affiliation with this project. If I'm wrong, I'll gladly modify my posts. Yes, posts, because I'm copying this everywhere that he copied his post.

**Comment by t00thpick1** [comment] 2017-09-01 03:58
Unable to reproduce running spigot 1.12.1 and mcMMo current source.  Hoppers work in the nether.

**Closed by t00thpick1** 2017-09-01 03:58 UTC
