### ISSUE TITLE
1.13 chop tree err

### ISSUE THREAD

**Issue by JackWisdom** [mcMMO-Dev/mcMMO#3516] opened 2018-07-29 04:11 UTC
version: 1.6 build 32
nullpoint err happened while chopping tree 
https://pastebin.com/Mtb7qUEN

**Comment by Glitchfinder** [comment] 2018-07-29 05:03
Duplicate of #3515 and #3514, currently already in the [1.13 bug megathread](https://github.com/mcMMO-Dev/mcMMO/issues/3498).

**Closed by Glitchfinder** 2018-07-29 05:03 UTC
