### ISSUE TITLE
[mcMMO] There was an error while enabling mcMMO!

### ISSUE THREAD

**Issue by andrewkm** [mcMMO-Dev/mcMMO#4717] opened 2022-01-11 23:43 UTC
mcMMO built on: https://github.com/mcMMO-Dev/mcMMO/commit/5d2028b5dc79f26b329a302e8a567eb2399c607b

```
[18:37:59] [Server thread/INFO]: [mcMMO] Enabling mcMMO v2.1.208
[18:37:59] [Server thread/INFO]: [mcMMO] [config] Initializing config: config.yml
[18:37:59] [Server thread/INFO]: [mcMMO] [config] Loading config from disk: config.yml
[18:37:59] [Server thread/ERROR]: [mcMMO] There was an error while enabling mcMMO!
[18:37:59] [Server thread/WARN]: java.lang.NoSuchMethodError: 'org.bukkit.configuration.file.YamlConfigurationOptions org.bukkit.configuration.file.YamlConfigurationOptions.parseComments(boolean)'
[18:37:59] [Server thread/WARN]: 	at mcMMO.jar//com.gmail.nossr50.config.BukkitConfig.initConfig(BukkitConfig.java:63)
[18:37:59] [Server thread/WARN]: 	at mcMMO.jar//com.gmail.nossr50.config.BukkitConfig.<init>(BukkitConfig.java:27)
[18:37:59] [Server thread/WARN]: 	at mcMMO.jar//com.gmail.nossr50.config.GeneralConfig.<init>(GeneralConfig.java:24)
[18:37:59] [Server thread/WARN]: 	at mcMMO.jar//com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:166)
[18:37:59] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[18:37:59] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[18:37:59] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[18:37:59] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561)
[18:37:59] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475)
[18:37:59] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:733)
[18:37:59] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:317)
[18:37:59] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1220)
[18:37:59] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[18:37:59] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[18:37:59] [Server thread/INFO]: [mcMMO] Disabling mcMMO v2.1.208
[18:37:59] [Server thread/INFO]: [mcMMO] Server shutdown has been executed, saving and cleaning up data...
[18:38:00] [Server thread/ERROR]: Error occurred while disabling mcMMO v2.1.208 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:361) ~[mcMMO.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[patched_1.17.1.jar:git-Paper-408]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[patched_1.17.1.jar:git-Paper-408]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[patched_1.17.1.jar:git-Paper-408]
	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:293) ~[mcMMO.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Paper-408]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-408]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-408]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Paper-408]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Paper-408]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:733) ~[patched_1.17.1.jar:git-Paper-408]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:317) ~[patched_1.17.1.jar:git-Paper-408]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[patched_1.17.1.jar:git-Paper-408]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-408]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "com.gmail.nossr50.config.AdvancedConfig.getCatalysisMaxBonusLevel()" because the return value of "com.gmail.nossr50.mcMMO.getAdvancedConfig()" is null
	at com.gmail.nossr50.skills.alchemy.Alchemy.<clinit>(Alchemy.java:49) ~[mcMMO.jar:?]
	... 15 more
```

Culprit is this commit: https://github.com/mcMMO-Dev/mcMMO/commit/c21a040ddbb92d22e5898eb1ae14d2e9fc5e6ab8
Builds prior work.

**Comment by Chew** [comment] 2022-01-11 23:50
Duplicate of #4716, will be closing in favor of that. Sorry for the issues :(

**Closed by Chew** 2022-01-11 23:50 UTC
