### ISSUE TITLE
Lag Issues in 1.9

### ISSUE THREAD

**Issue by eGuru14** [mcMMO-Dev/mcMMO#2912] opened 2016-04-22 16:15 UTC
I'm having some issues with lag on my 1.9 server, especially with regards to tree harvesting. I can tell that McMMO is what's causing it, because the issue is gone after I temporarily removed the plugin. When I break wood, the item can't be picked up, and will continue to fall to the ground, disappear, reappear in midair, and repeat the process. Anybody have an idea as to a solution?

(Sorry if I didn't include any log files or anything that you guys need, I'm new to github)

**Comment by Azfaloth** [comment] 2016-05-16 07:17
I am experiencing a similar issue in 1.9.2 with the latest jenkins build. Even swords, axes and mining lags. Everytime a player levels up swords, axes, woodcutting or mining, the game freezes for the player who levelled up for approx 3-4 seconds and then catches up. This is terribly annoying for players who constantly complain of lag. The lag doesnt appear in worlds where mcmmo is off(using the permissions). It has also appeared a few times when passive abilities fired and displayed messages like "Enemy bleeding" on screen. But it always happens when a player levels up mcmmo and theres a few seconds of client freeze time before the message appears and they catch up with the rest of the world,

I've been using mcmmo since 1.5 years and this problem has only appeared since 1.9.

**Comment by EvilOlaf** [comment] 2016-05-16 07:34
You could run and past a timing sheet to get an idea which event causes the freeze.

**Comment by Azfaloth** [comment] 2016-05-16 08:12
Yeah I will do that now. The strange thing is that everyone on the server doesnt lag when this happens. Only the player who was involved in the mcmmo thing. But I will run timings just to get a clearer picture of what might be happening. I am using flatfile storage and I switched on the purge old users setting. I'm hoping that will help as well. I will post back here with any results I get.

**Comment by EvilOlaf** [comment] 2016-05-16 08:16
Do you run your mc server on a vps? maybe the hard drive is on overload?
You can also give PaperSpigot a try, because they implemented a way more detailed timings sheet.

**Comment by Azfaloth** [comment] 2016-05-16 14:17
The server is hosted on beastnode. They have ssds and this mystery lag seems to have abruptly started in 1.9. Yeah I've been meaning to try and check out paper spigot. I think I will.

In any case, this is what timings tells me. This was run for half an hour with one player on who ran around farming, used treefeller two times, was fighting a lot of mobs and wandering the map generally.

The only major lag sources marked in red were the world save event and unfortunately mcmmo.

http://imgur.com/171ZPGa

The "Task: ScoreboardWrapper$ScoreboardChangeTask(Single)" and
"SelfListener::onPlayerLevelUp(McMMOPlayerLevelUpEvent)"

**Comment by Azfaloth** [comment] 2016-05-17 06:26
Yep. Edited the config and turned off the scoreboard display on levelling up and the lag incidents went away. I think theres something wrong with the scoreboard tasks. Hope this helps someone else! Good day to you all. Thanks EvilOlaf for helping with the issue! :)

**Comment by Deiscorides** [comment] 2016-09-02 12:05
I have the same trouble on a server (Spigot 1.10) I frequent. My client will freeze up a few moments before the scoreboard is able to display when I level up. It unfreezes while the scoreboard is displayed, for a few seconds then freezes again when the scoreboard disappears. My personal work around for this on servers is this command:

/mcscoreboard time 0

I use it immediately when I log into the server. If I level up, I only get the chat notification. However, if I use this command after a scoreboard has popped up, it will pop up that scoreboard again and leave it there; yet that scoreboard won't update. Thus, after using this command I never have the level up lag associated with the scoreboard. It needs to be used every time you login to a server. Don't use the command during the level up client lag spike it sometimes doesn't work then.

I hope this helps those of you who are not the server's admin. Hopefully, this problem will be fixed soon.

**Comment by Azfaloth** [comment] 2016-09-02 12:19
The cause of this issue is not exactly mcMMO. This is a Spigot bug or a bug in other plugins that use scoreboards to store data like citizens and mythic mobs and maybe mcmmo(not sure). Turns out that scoreboard handling has changed at some point, and empty scoreboard entries are no longer cleared from the scoreboard.dat file in the world folder. Over time, the scoreboard gets huge and leads to lag spikes whenever scoreboards are accessed. 

Deleting the scoreboard.dat file leads to a temporary solution but the scoreboard quickly gets filled up with junk again, lagging the server. Some threads about this issue are:

https://www.spigotmc.org/threads/1-9-downloading-terrain-timed-out.136765/
https://github.com/PaperMC/Paper/issues/244

Timings will show a huge lag in "world save" because of the increased size of the scoreboard.dat file.

Ask the owner of your server to install this plugin
https://www.spigotmc.org/resources/scoreboardhotfix-fixes-1-9-scoreboard-bug.22678/

This will not help if the server is running mythicmobs. That has a different fix for the empty scoreboard entries it creates for every single mob in the map.

**Closed** 2018-07-24 23:57 UTC
