### ISSUE TITLE
Alchemy not working 1.13.1

### ISSUE THREAD

**Issue by Daedaliss** [mcMMO-Dev/mcMMO#3607] opened 2018-10-22 18:47 UTC
I have tried everything, but no matter what I change I can't get alchemy to brew potions correctly or give the correct amount of exp

**Comment by DiamondDagger590** [comment] 2018-11-08 20:19
They changed the way potions work in 1.13 I believe in the conversion of item IDS. thus this might be the cause of the issue. Is this able to be duplicated in 1.13 or 1.13.2?

**Comment by RowanUnderwood** [comment] 2018-12-02 22:32
> They changed the way potions work in 1.13 I believe in the conversion of item IDS. thus this might be the cause of the issue. Is this able to be duplicated in 1.13 or 1.13.2?

Yea, I have the same issue in 13.2

**Comment by t00thpick1** [comment] 2018-12-02 23:54
This should be fixed in latest dev builds.

**Comment by t00thpick1** [comment] 2018-12-02 23:55
See #3564

**Closed by t00thpick1** 2018-12-02 23:55 UTC
