### ISSUE TITLE
Fall damage

### ISSUE THREAD

**Issue by Jonathanshakib** [mcMMO-Dev/mcMMO#3255] opened 2017-08-10 18:12 UTC
When you fall with armor you instantly die

**Comment by AllPlayed** [comment] 2017-08-15 13:06
Hello
This will be fixed with the new 1.12.1 version of MCMMO, just be patient 🙂

**Comment by ezeiger92** [comment] 2017-08-15 21:26
Be skeptical of @AllPlayed, I have not seen a single piece of evidence that he has any affiliation with this project. If I'm wrong, I'll gladly modify my posts. Yes, posts, because I'm copying this everywhere that he copied his post.

**Comment by t00thpick1** [comment] 2017-09-01 04:50
Unable to reproduce in spigot 1.12.1 with latest mcMMO version.

**Closed by t00thpick1** 2017-09-01 04:50 UTC
