### ISSUE TITLE
Could not pass event BrewEvent to mcMMO v2.1.202

### ISSUE THREAD

**Issue by haroldrc** [mcMMO-Dev/mcMMO#4712] opened 2022-01-07 14:29 UTC
java.lang.NoSuchMethodError: 'void org.bukkit.event.inventory.BrewEvent.<init>(org.bukkit.block.Block, org.bukkit.inventory.BrewerInventory, int)'
        at com.gmail.nossr50.events.fake.FakeBrewEvent.<init>(FakeBrewEvent.java:9) ~[mcMMO.jar:?]
        at com.gmail.nossr50.skills.alchemy.AlchemyPotionBrewer.finishBrewing(AlchemyPotionBrewer.java:136) ~[mcMMO.jar:?]
        at com.gmail.nossr50.runnables.skills.AlchemyBrewTask.finishImmediately(AlchemyBrewTask.java:111) ~[mcMMO.jar:?]
        at com.gmail.nossr50.listeners.InventoryListener.onBrew(InventoryListener.java:356) ~[mcMMO.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor504.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Airplane-112]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.17.1.jar:git-Airplane-112]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Airplane-112]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Airplane-112]
        at net.minecraft.world.level.block.entity.BrewingStandBlockEntity.a(BrewingStandBlockEntity.java:260) ~[app:?]
        at net.minecraft.world.level.block.entity.BrewingStandBlockEntity.serverTick(BrewingStandBlockEntity.java:184) ~[app:?]
        at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.tick(LevelChunk.java:1491) ~[app:?]
        at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.tick(LevelChunk.java:1443) ~[app:?]
        at net.minecraft.world.level.Level.tickBlockEntities(Level.java:1066) ~[app:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:796) ~[app:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1627) ~[patched_1.17.1.jar:git-Airplane-112]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:492) ~[patched_1.17.1.jar:git-Airplane-112]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[patched_1.17.1.jar:git-Airplane-112]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[patched_1.17.1.jar:git-Airplane-112]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Airplane-112]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by CheesyTheArtist** [comment] 2022-01-07 15:14
Update mcmmo. already patched. Plus you've already created a issue simmilar to this, and yet did once again?

**Comment by Chew** [comment] 2022-01-07 19:05
Yeah Duplicate of your own issue... #4691 

Please provide a FULL log if you're SURE you're fully up to date.

**Closed by Chew** 2022-01-07 19:05 UTC
