### ISSUE TITLE
Cannot Load Player Data

### ISSUE THREAD

**Issue by JammMusic** [mcMMO-Dev/mcMMO#2346] opened 2014-11-06 23:33 UTC
"Mcmmo still cannot load your data. You may want to contact the server owner."
Random players are getting this message on my server. Players who have the message have had all their stats reset to 0. This happened after updating the plugin to 1.5.01-SNAPSHOT-b3686.

I am using Spigot 1.7.10

**Comment by TfT-02** [comment] 2015-01-10 11:37
This ticket is a duplicate of https://github.com/mcMMO-Dev/mcMMO/issues/2225, please refer to that ticket and post your findings or questions on there. We're aware of this issue and are working on a fix.

**Closed by TfT-02** 2015-01-10 11:37 UTC
Labels: Confirmed Bug, Duplicate
