### ISSUE TITLE
There was an error while enabling mcMMO!

### ISSUE THREAD

**Issue by 21MX** [mcMMO-Dev/mcMMO#4828] opened 2022-09-26 11:42 UTC
Logs: https://pastebin.com/Y730uRgh

**Comment by Greymagic27** [comment] 2022-09-26 12:53
See if the issue happens when using paper. I don't believe forge is fully supported yet

**Comment by 21MX** [comment] 2022-09-26 12:56
I use the latest Minecraft Magma version with Forge & Spigot

**Comment by Greymagic27** [comment] 2022-09-26 12:58
Magma isn't fully supported. See https://github.com/mcMMO-Dev/mcMMO/issues/4824#issuecomment-1232281092

**Comment by Chew** [comment] 2022-09-26 16:24
Closing as a duplicate of #4824, please also avoid Forge+Bukkit hybrids as they cause unstable stuff like this.

**Closed by Chew** 2022-09-26 16:24 UTC
