### ISSUE TITLE
Dev build link not working

### ISSUE THREAD

**Issue by CraftingBro** [mcMMO-Dev/mcMMO#3321] opened 2017-10-14 10:33 UTC
When trying to download one of the dev builds without the paywall (I'm poor) the link returns a "bad gateway" error 502. Please fix this!

**Comment by t00thpick1** [comment] 2017-10-14 17:08
It goes down sometimes, give it a few days

**Comment by popcorn9499** [comment] 2017-10-14 18:04
the dev link went down permenantly it sounds like. His other project essentialsx on that same jenkins is also down. There was a mirror but that doesnt appear to have this

**Comment by popcorn9499** [comment] 2017-10-14 18:12
I just created a mirror jenkins that will work if anyone wants it. If there are any issues please don't hesitate to contact me https://popicraft.net/jenkins/job/mcMMO/
Hopefully this helps. The owner of that jenkins is apparnetly not keeping it up anymore https://twitter.com/drtshock/status/918913335008964608

**Comment by t00thpick1** [comment] 2017-10-14 22:40
oh hey. looks like it is down... huh.

**Comment by popcorn9499** [comment] 2017-10-15 04:53
yep sadly. Ill try to keep that mirror up if you all want to use it. alright?

**Comment by arcan9ne** [comment] 2017-10-15 19:28
Unfortunately its down :( it also doesnt run on the link provided by @popcorn9499 but i think its the wrong version. I am trying to add mcMMO to minecraft version 1.8.9, I had it on a private server a few months ago and came back to make another similar server but can't seem to find a compatible version anywhere.

Anything I can do @t00thpick1 @popcorn9499 

Thanks

**Comment by popcorn9499** [comment] 2017-10-15 21:54
What are you meaning @arcan9ne ? I thought mine was up to date with the current version and i thought that jenkins server was online. i am on it as of right now and it works flawlessly for me.

**Comment by mastercheem** [comment] 2017-10-15 23:20
@popcorn9499 Your link doesn't work, any other way you could send me the file? I could put a mirror up on google drive or something at least.

**Comment by popcorn9499** [comment] 2017-10-15 23:25
Like i just said i accidentally killed it just give me a minute.

**Comment by arcan9ne** [comment] 2017-10-15 23:28
Thanks for the response @popcorn9499,

Im trying to run it on minecraft version 1.8.9 but it simply doesn't do anything, other plugins such as sethome are installed and appear green when /plugins is typed, however mcmmo always come up as red and fails to install.

It used to be fine on a server a made back in July and have tried multiple mcmmo releases, the link for the 1.5.04 snapshot is unavailable but I think I tried that before.

If there's any more information you require from me I can surely provide if you can help me. I'm not too technically training so please bear with me

**Comment by popcorn9499** [comment] 2017-10-15 23:47
@arcan9ne Could you please run just mcMMO and then send me the server log? another thing that may be useful is the version of java ur running? to help more I would need to know what operating system your running? and any questions please feel free to ask ill gladly try to help the best i can

**Comment by popcorn9499** [comment] 2017-10-15 23:57
btw just to let you know @mastercheem I have the jenkins link back up https://popicraft.net/jenkins/job/mcMMO/ so just go there and it should work to the best of my knowledge. Sorry about the downtime

**Comment by arcan9ne** [comment] 2017-10-16 11:45
hi @popcorn9499, the server is currently on Java version 8

https://pastebin.com/pMTGBde7

This is the pastebin of the console log which has the orange/red errors regarding mcmmo, I hope this is what you're asking for? OS is windows 10 home 64bit.

The server is being hosted by server.pro (the same one I used in July where it worked)

Thanks again

**Comment by SXRWahrheit** [comment] 2017-10-16 15:21
@arcan9ne You're trying to run a newer build on an old server version. It can't find Mending because Mending was added in 1.9, and you are on 1.8. You will need to run a build that was compiled for 1.8.

**Comment by arcan9ne** [comment] 2017-10-16 17:04
@SXRWahrheit Yes I thought that, but in my 1.8.x server in July I was able to download the previous mcMMO version and it ran perfectly.

The problem is that with the devbuild site (drtshock) being down, I can't find the version i'm looking for to run on 1.8.x, only the newest build is available which doesn't work for me.

**Comment by SXRWahrheit** [comment] 2017-10-16 17:31
You'd want to make a separate issue for that, and I'm sure there is already one that exists.

Other users have commented about it on the Spigot thread and the author is aware.

**Comment by popcorn9499** [comment] 2017-10-16 20:27
if i could help i would but idk where a 1.8 build would be. thats like a few years old now is it not?

**Comment by SXRWahrheit** [comment] 2017-10-16 20:41
Yes, 1.8 was released in summer 2015.

**Comment by arcan9ne** [comment] 2017-10-16 21:34
@popcorn9499 @SXRWahrheit yes its old, but with the dev site down I just can't find an alternative download for it :(

**Comment by Nicofisi** [comment] 2017-10-27 19:22
@popcorn9499 thanks for the mirror!

**Closed** 2017-10-28 00:21 UTC

**Comment by Nicofisi** [comment] 2017-10-28 09:35
@popcorn9499 looks like your mirror is the "official" one on https://www.spigotmc.org/resources/mcmmo.2445/ , wp

**Comment by popcorn9499** [comment] 2017-10-28 15:12
Im kinda surprised mine became the official mirror tbh. Anyways @Nicofisi  Thanks for letting me know. If there r issues with that mirror im still learning github
