### ISSUE TITLE
[Bug] Death Messages issue by Mcmmo (After paper adventure update)

### ISSUE THREAD

**Issue by slvlr** [mcMMO-Dev/mcMMO#4448] opened 2021-03-11 12:51 UTC
I reported it to Paper, but it turns out it's Mcmmo causing the issue: https://github.com/PaperMC/Paper/issues/5332

Death messages are no longer displaying in colour, and the item text is no longer "hoverable" 
Mcmmo build 2.1.179

**Comment by nossr50** [comment] 2021-03-30 22:58
Duplicate of #4463

**Closed by nossr50** 2021-03-30 22:58 UTC
