### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by TheBlueKingLP** [mcMMO-Dev/mcMMO#2661] opened 2015-08-15 19:12 UTC
If I use silk touch pickaxe to break the diamond ore to bring it home, place it, and use the piston to PALL it, using silk touch pickaxe to break it again, it will be doubled
p.s. i am newest version

**Comment by bm01** [comment] 2015-08-15 21:36
Duplicate of #2655

**Closed by bm01** 2015-08-15 21:36 UTC
Labels: Duplicate
