### ISSUE TITLE
add /mcmmo reload

### ISSUE THREAD

**Issue by MentosPL** [mcMMO-Dev/mcMMO#3347] opened 2017-12-06 16:44 UTC
i don't want use /reload, with 60 players online and 70 plugins, 
and /reload command crashes many plugins and isn't recomended.

**Comment by Flavourized** [comment] 2017-12-12 08:16
plugman

**Comment by MentosPL** [comment] 2017-12-17 21:19
nope, add the command C:

**Comment by TNTUP** [comment] 2017-12-18 11:31
That could be useful while tweaking up settings instead of rebooting the server

**Comment by Glitchfinder** [comment] 2018-04-07 18:07
Duplicate of #209. Also, this is not possible with the current setup mcMMO has. A few years back, when that issue was being actively commented on, it was possible, and I almost got it into the plugin. However, with the way this plugin currently uses some features of Java, reloading it will break the it entirely.

**Closed by Glitchfinder** 2018-04-07 18:07 UTC
Labels: Duplicate, Feature Request
