### ISSUE TITLE
Blaze Powder as Fuel issue

### ISSUE THREAD

**Issue by cunningdevil666** [mcMMO-Dev/mcMMO#2873] opened 2016-03-30 13:21 UTC
Hi! I'm an administrator of a server, which runs McMMO. We currently running the 1.5.04-b123 version.
There seems to be an issue with the blaze powder as a fuel. If the blaze powder is in the fuel slot of the brewing stand at the moment of previous fuel finishing, the brewing stand will just burn through all of the blaze powder in the fuel slot in matter of seconds.
This has been tested, and it was confirmed that this happens only with McMMO (no other plugins play a role into this).

**Comment by clovisd** [comment] 2016-03-30 21:16
I've had the same problem on my server.

**Comment by t00thpick1** [comment] 2016-03-30 23:06
Looking into it, thanks for the report

**Comment by clovisd** [comment] 2016-04-05 07:43
Any news or updates on this? Thank you!

**Comment by t00thpick1** [comment] 2016-04-05 14:32
@clovisd Expect this and a few other issues to be fixed within the next few days.

**Comment by sigmaroot** [comment] 2016-04-21 19:48
Running mcMMO-1.5.05-b134, this is not fixed.

**Comment by sigmaroot** [comment] 2016-05-28 14:46
Running mcMMO-1.5.05-b136, this is not fixed. :(

**Comment by t00thpick1** [comment] 2016-05-30 03:04
Sorry life got really really busy.  I'm trying to get back on development this week.

**Comment by minoneer** [comment] 2016-06-09 00:21
Same problem here. It turns out the problem is that the fuel level is set with each tick. That usually isn't a problem, except when it is set to 0. The potion stand refills the level to 20, using 1 fuel item. But the next tick, mcMMO resets it to 0, another item is consumed, and so on, until there are no more items left.
I fixed it for our server and provided it as PR, in case you are interested.

**Closed** 2016-06-25 16:53 UTC
