### ISSUE TITLE
Smelting error

### ISSUE THREAD

**Issue by MrKiller01** [mcMMO-Dev/mcMMO#3569] opened 2018-09-16 11:35 UTC
I don't know if other members were doing this, I was smelting weapons and that resulted in an error. Earlier version, a golden sword with curse of binding (Elitemobs) I got rid off through smelting...
Then only diamonds left... better than useless sword.

```
 [13:31:19 ERROR]: Could not pass event FurnaceSmeltEvent to mcMMO v1.6.0-SNAPSHOT
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.1.jar:git-Spigot-6b015b4-94b8708]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.1.jar:git-Spigot-6b015b4-94b8708]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.13.1.jar:git-Spigot-6b015b4-94b8708]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.13.1.jar:git-Spigot-6b015b4-94b8708]
        at net.minecraft.server.v1_13_R2.TileEntityFurnace.burn(TileEntityFurnace.java:362) [spigot-1.13.1.jar:git-Spigot-6b015b4-94b8708]
        at net.minecraft.server.v1_13_R2.TileEntityFurnace.Y_(TileEntityFurnace.java:308) [spigot-1.13.1.jar:git-Spigot-6b015b4-94b8708]
        at net.minecraft.server.v1_13_R2.World.tickEntities(World.java:1247) [spigot-1.13.1.jar:git-Spigot-6b015b4-94b8708]
        at net.minecraft.server.v1_13_R2.WorldServer.tickEntities(WorldServer.java:601) [spigot-1.13.1.jar:git-Spigot-6b015b4-94b8708]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:972) [spigot-1.13.1.jar:git-Spigot-6b015b4-94b8708]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:411) [spigot-1.13.1.jar:git-Spigot-6b015b4-94b8708]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.1.jar:git-Spigot-6b015b4-94b8708]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.1.jar:git-Spigot-6b015b4-94b8708]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.IllegalArgumentException: Cannot get data for not block POTATO
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191) ~[spigot-1.13.1.jar:git-Spigot-6b015b4-94b8708]
        at org.bukkit.craftbukkit.v1_13_R2.block.data.CraftBlockData.newData(CraftBlockData.java:472) ~[spigot-1.13.1.jar:git-Spigot-6b015b4-94b8708]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.createBlockData(CraftServer.java:1831) ~[spigot-1.13.1.jar:git-Spigot-6b015b4-94b8708]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.createBlockData(CraftServer.java:1806) ~[spigot-1.13.1.jar:git-Spigot-6b015b4-94b8708]
        at org.bukkit.Bukkit.createBlockData(Bukkit.java:1186) ~[spigot-1.13.1.jar:git-Spigot-6b015b4-94b8708]
        at org.bukkit.Material.createBlockData(Material.java:1986) ~[spigot-1.13.1.jar:git-Spigot-6b015b4-94b8708]
        at com.gmail.nossr50.util.ItemUtils.isSmeltable(ItemUtils.java:514) ~[?:?]
        at com.gmail.nossr50.listeners.InventoryListener.onFurnaceSmeltEvent(InventoryListener.java:111) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor282.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.1.jar:git-Spigot-6b015b4-94b8708]
        ... 12 more
```

**Comment by Glitchfinder** [comment] 2018-09-16 15:34
It looks like the issue is caused by cooking a potato, which shouldn't be happening. The specific line causing the error is [this one](https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/java/com/gmail/nossr50/util/ItemUtils.java#L514), which is set up to prevent non-blocks from causing that exception in the first place. This error will take some significant digging to sort out, I think.

**Comment by t00thpick1** [comment] 2018-10-10 01:57
Should be fixed in latest build.

**Closed by t00thpick1** 2018-10-10 01:57 UTC
