### ISSUE TITLE
HEARTS killed by player - bugged message when killing a tamed wolf / ocelot.

### ISSUE THREAD

**Issue by bloggy** [mcMMO-Dev/mcMMO#2434] opened 2015-01-26 21:34 UTC
![2015-01-26_22 33](https://cloud.githubusercontent.com/assets/6141938/5908892/b0318b60-a5ab-11e4-993a-6d7384356328.jpg)
Mcmmo config:

Mob_Healthbar:
    # Display_Type: Default display for mob health bars - HEARTS, BAR, or DISABLED
    # Display_Time: Amount of time (in seconds) to display. To display permanently, set to -1
    Display_Type: DISABLED

Even with the option being disabled there appears a message in chat when a player kills a tamed wolf / ocelot. See screenshot:

![2015-01-26_22 33](https://cloud.githubusercontent.com/assets/6141938/5908868/7f0900b8-a5ab-11e4-886e-456a0c0d7cb6.jpg)

Can you fix it?

mcmmo version 1.5.01

**Comment by TfT-02** [comment] 2015-02-28 15:08
Duplicate of https://github.com/mcMMO-Dev/mcMMO/issues/1726
Negate the permission node `mcmmo.mobhealthdisplay` to disable the health bars. The setting you are talking about only changes the default setting, for when a player logs in for the first time.

**Closed by TfT-02** 2015-02-28 15:08 UTC
