### ISSUE TITLE
Plugin not started

### ISSUE THREAD

**Issue by PixelJames22** [mcMMO-Dev/mcMMO#4719] opened 2022-01-12 14:29 UTC
Hi there,

Having an issue with version 2.1.208 on the server. I backed up and deleted all files yet still had this issue on server startup. Running Paper Spigot version 1.18.1

`[14:20:58] [Server thread/INFO]: [mcMMO] Enabling mcMMO v2.1.208
[14:20:58] [Server thread/INFO]: [mcMMO] [config] Initializing config: config.yml
[14:20:58] [Server thread/INFO]: [mcMMO] [config] User config file not found, copying a default config to disk: config.yml
[14:20:58] [Server thread/INFO]: [mcMMO] [config] Loading config from disk: config.yml
[14:20:58] [Server thread/ERROR]: [mcMMO] There was an error while enabling mcMMO!
[14:20:58] [Server thread/WARN]: java.lang.NoSuchMethodError: 'org.bukkit.configuration.file.YamlConfigurationOptions org.bukkit.configuration.file.YamlConfigurationOptions.parseComments(boolean)'
[14:20:58] [Server thread/WARN]: 	at mcMMO.jar//com.gmail.nossr50.config.BukkitConfig.initConfig(BukkitConfig.java:63)
[14:20:58] [Server thread/WARN]: 	at mcMMO.jar//com.gmail.nossr50.config.BukkitConfig.<init>(BukkitConfig.java:27)
[14:20:58] [Server thread/WARN]: 	at mcMMO.jar//com.gmail.nossr50.config.GeneralConfig.<init>(GeneralConfig.java:24)
[14:20:58] [Server thread/WARN]: 	at mcMMO.jar//com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:166)
[14:20:58] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[14:20:58] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[14:20:58] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[14:20:58] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:563)
[14:20:58] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:477)
[14:20:58] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727)
[14:20:58] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503)
[14:20:58] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:313)
[14:20:58] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1202)
[14:20:58] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[14:20:58] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[14:20:58] [Server thread/INFO]: [mcMMO] Disabling mcMMO v2.1.208
[14:20:58] [Server thread/INFO]: [mcMMO] Server shutdown has been executed, saving and cleaning up data...
[14:20:58] [Server thread/ERROR]: Error occurred while disabling mcMMO v2.1.208 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:361) ~[mcMMO.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:293) ~[mcMMO.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.18.1.jar:git-Paper-82]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[paper-1.18.1.jar:git-Paper-82]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727) ~[paper-1.18.1.jar:git-Paper-82]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503) ~[paper-1.18.1.jar:git-Paper-82]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.1.jar:git-Paper-82]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.1.jar:git-Paper-82]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-82]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "com.gmail.nossr50.config.AdvancedConfig.getCatalysisMaxBonusLevel()" because the return value of "com.gmail.nossr50.mcMMO.getAdvancedConfig()" is null
	at com.gmail.nossr50.skills.alchemy.Alchemy.<clinit>(Alchemy.java:49) ~[mcMMO.jar:?]
	... 16 more`

Any ideas on how to fix this? Didn't have any issues with the last versions so looking forward to having it active again!

Not sure what "[mcMMO] Server shutdown has been executed, saving and cleaning up data..." means, as this is in the middle of startup.

Thanks for your work,

~James

**Comment by TheBusyBiscuit** [comment] 2022-01-12 14:42
Duplicate of #4716

Don't worry, a fix has already been pushed, so the next release should no longer be affected by this issue :)

**Closed** 2022-01-12 19:28 UTC
Labels: Duplicate
