### ISSUE TITLE
Warning Tips When Using PaperSpigot

### ISSUE THREAD

**Issue by abc605521864** [mcMMO-Dev/mcMMO#3437] opened 2018-04-28 01:58 UTC
This warning does not appear under spigot, please fix it
`[09:41:04 INFO]: [mcMMO] Enabling mcMMO v1.5.09-SNAPSHOT
[09:41:06 INFO]: [mcMMO] Killing orphans
[09:41:06 WARN]: java.lang.Throwable: Warning: A plugin is creating a recipe using a Deprecated method. This will cause you to receive warnings stating 'Tried to load unrecognized recipe: bukkit:<ID>'. Please ask the author to give their recipe a static key using NamespacedKey.
[09:41:06 WARN]:        at org.bukkit.inventory.ShapelessRecipe.<init>(ShapelessRecipe.java:26)
[09:41:06 WARN]:        at com.gmail.nossr50.util.ChimaeraWing.getChimaeraWingRecipe(ChimaeraWing.java:164)
[09:41:06 WARN]:        at com.gmail.nossr50.mcMMO.registerCustomRecipes(mcMMO.java:437)
[09:41:06 WARN]:        at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:167)
[09:41:06 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[09:41:06 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[09:41:06 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[09:41:06 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:387)
[09:41:06 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:336)
[09:41:06 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:226)
[09:41:06 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[09:41:06 WARN]:        at java.lang.Thread.run(Thread.java:748)`

**Comment by Glitchfinder** [comment] 2018-04-28 05:08
Duplicate of #3358, #3411, #3416, and #3434. This has been fixed as of https://github.com/mcMMO-Dev/mcMMO/commit/d4f2f0e11b538d0ee9ea06d91578a291b35c36a1, and will be in the next build uploaded to Spigot's website.

**Closed by Glitchfinder** 2018-04-28 05:08 UTC
Labels: Confirmed Bug, Duplicate, Fixed
