### ISSUE TITLE
ERROR:A plugin is creating a recipe using a Deprecated method.

### ISSUE THREAD

**Issue by smartmadio** [mcMMO-Dev/mcMMO#3416] opened 2018-03-18 00:12 UTC
> [08:06:37] [Server thread/WARN]: java.lang.Throwable: Warning: A plugin is creating a recipe using a Deprecated method. This will cause you to receive warnings stating 'Tried to load unrecognized recipe: bukkit:<ID>'. Please ask the author to give their recipe a static key using NamespacedKey.
[08:06:37] [Server thread/WARN]: 	at org.bukkit.inventory.ShapelessRecipe.<init>(ShapelessRecipe.java:26)
[08:06:37] [Server thread/WARN]: 	at com.gmail.nossr50.util.ChimaeraWing.getChimaeraWingRecipe(ChimaeraWing.java:164)
[08:06:37] [Server thread/WARN]: 	at com.gmail.nossr50.mcMMO.registerCustomRecipes(mcMMO.java:437)
[08:06:37] [Server thread/WARN]: 	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:167)
[08:06:37] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[08:06:37] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[08:06:37] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[08:06:37] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:387)
[08:06:37] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:336)
[08:06:37] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:226)
[08:06:37] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)

Spigot 1.12.2+Java8

**Comment by Glitchfinder** [comment] 2018-03-18 06:56
Duplicate of #3411

**Closed** 2018-03-18 06:57 UTC
Labels: Confirmed Bug, Duplicate, Fixed
