### ISSUE TITLE
Mining double drops dupe bug

### ISSUE THREAD

**Issue by Jasper51297** [mcMMO-Dev/mcMMO#2655] opened 2015-08-12 14:52 UTC
I just installed the latest version of mcmmo (1.5.01 -SNAPSHOT -b3682)
We are using this version of Spigot: git-spigot-870264a-0a645a2 (MC 1.8.3)
I was testing if the dupe problem was solved in the new version. I moved some diamond ore blocks with a piston, and mined it when I was done with a silk touch pickaxe. This worked fine, no double drops.

After that, I placed a diamond ore block next to a sticky piston, and started spamming the lever. It will 'glitch' if you spam it. (The piston won't pull the block back). If you mine the block with silktouch, you will get double drops. 
![2015-08-12_16 42 27](https://cloud.githubusercontent.com/assets/13767181/9226937/53844270-4111-11e5-85c8-eb1f697aca96.png)
![2015-08-12_16 43 07](https://cloud.githubusercontent.com/assets/13767181/9226938/5386cf40-4111-11e5-83c5-11635ab27109.png)

**Comment by EvilOlaf** [comment] 2015-08-12 16:37
Did you try this with the latest dev build too?

**Comment by bm01** [comment] 2015-08-12 21:43
I cannot reproduce it with 1.5.03-b62.

**Comment by PsychoNavigator** [comment] 2015-08-17 14:08
Don't you get double drops when your mining is above a specific level anyway? What is OP's mining level?

**Comment by t00thpick1** [comment] 2015-11-04 20:27
Fixed on newer builds

**Closed by t00thpick1** 2015-11-04 20:27 UTC
