### ISSUE TITLE
NoSuchMethod error on player join

### ISSUE THREAD

**Issue by Loving11ish** [mcMMO-Dev/mcMMO#4527] opened 2021-05-17 14:41 UTC
Hello there

A problem has started to occur when a player joins the server.  The following error is thrown in the console.

`java.lang.NoSuchMethodError: 'us.myles.ViaVersion.api.protocol.ServerProtocolVersion us.myles.ViaVersion.api.ViaAPI.getServerVersion()'
17.05 08:38:16 [Server] INFO at com.gmail.nossr50.mcmmo.kyori.adventure.platform.viaversion.ViaFacet.isApplicable(ViaFacet.java:91) ~[?:?]
17.05 08:38:16 [Server] INFO at com.gmail.nossr50.mcmmo.kyori.adventure.platform.facet.Facet.of(Facet.java:100) ~[?:?]
17.05 08:38:16 [Server] INFO at com.gmail.nossr50.mcmmo.kyori.adventure.platform.facet.FacetAudience.<init>(FacetAudience.java:104) ~[?:?]
17.05 08:38:16 [Server] INFO at com.gmail.nossr50.mcmmo.kyori.adventure.platform.bukkit.BukkitAudience.<init>(BukkitAudience.java:85) ~[?:?]
17.05 08:38:16 [Server] INFO at com.gmail.nossr50.mcmmo.kyori.adventure.platform.bukkit.BukkitAudiencesImpl.createAudience(BukkitAudiencesImpl.java:162) ~[?:?]
17.05 08:38:16 [Server] INFO at com.gmail.nossr50.mcmmo.kyori.adventure.platform.bukkit.BukkitAudiencesImpl.createAudience(BukkitAudiencesImpl.java:71) ~[?:?]
17.05 08:38:16 [Server] INFO at com.gmail.nossr50.mcmmo.kyori.adventure.platform.facet.FacetAudienceProvider.lambda$addViewer$0(FacetAudienceProvider.java:89) ~[?:?]
17.05 08:38:16 [Server] INFO at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705) ~[?:?]
17.05 08:38:16 [Server] INFO at com.gmail.nossr50.mcmmo.kyori.adventure.platform.facet.FacetAudienceProvider.addViewer(FacetAudienceProvider.java:88) ~[?:?]
17.05 08:38:16 [Server] INFO at com.gmail.nossr50.mcmmo.kyori.adventure.platform.bukkit.BukkitAudiencesImpl.lambda$new$3(BukkitAudiencesImpl.java:101) ~[?:?]
17.05 08:38:16 [Server] INFO at com.gmail.nossr50.mcmmo.kyori.adventure.platform.bukkit.BukkitAudiencesImpl.lambda$registerEvent$5(BukkitAudiencesImpl.java:215) ~[?:?]
17.05 08:38:16 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-670]
17.05 08:38:16 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-670]
17.05 08:38:16 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-670]
17.05 08:38:16 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerList.postChunkLoadJoin(PlayerList.java:356) ~[patched_1.16.5.jar:git-Paper-670]
17.05 08:38:16 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerList.lambda$null$1(PlayerList.java:303) ~[patched_1.16.5.jar:git-Paper-670]
17.05 08:38:16 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.tick(PlayerConnection.java:316) ~[patched_1.16.5.jar:git-Paper-670]
17.05 08:38:16 [Server] INFO at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:408) ~[patched_1.16.5.jar:git-Paper-670]
17.05 08:38:16 [Server] INFO at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:159) ~[patched_1.16.5.jar:git-Paper-670]
17.05 08:38:16 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1512) ~[patched_1.16.5.jar:git-Paper-670]
17.05 08:38:16 [Server] INFO at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:419) ~[patched_1.16.5.jar:git-Paper-670]
17.05 08:38:16 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1339) ~[patched_1.16.5.jar:git-Paper-670]
17.05 08:38:16 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1127) ~[patched_1.16.5.jar:git-Paper-670]
17.05 08:38:16 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Paper-670]
17.05 08:38:16 [Server] INFO at java.lang.Thread.run(Thread.java:829) [?:?]`

Hopefully, this isn't anything game breaking.

**Comment by cloakfox** [comment] 2021-05-18 11:10
Getting same error
https://gist.github.com/cloakfox/ab3c3b4ef478be3c2a6e47f7f8f4ac7d

**Comment by b01w** [comment] 2021-05-19 00:18
Getting the same error too, running the exact same, super annoying haha

**Comment by EuanM199** [comment] 2021-05-23 12:50
Getting same error, really annoying

**Comment by CheesyTheArtist** [comment] 2021-05-23 13:05
This issue is well known by now. The fix for this issue is to update ViaVersion (ViaBackwars too, if used) to the latest **dev** build and the issue should be resolved.

**Comment by cloakfox** [comment] 2021-05-23 13:14
> This issue is well known by now. The fix for this issue is to update ViaVersion (ViaBackwars too, if used) to the latest **dev** build and the issue should be resolved.

That does not sound like a fix of the issue

**Comment by CheesyTheArtist** [comment] 2021-05-23 14:31
> 
> 
> > This issue is well known by now. The fix for this issue is to update ViaVersion (ViaBackwars too, if used) to the latest **dev** build and the issue should be resolved.
> 
> That does not sound like a fix for the issue

That's generally the fix, or that's what nossr50 said in the discord a month back.
![image](https://user-images.githubusercontent.com/69735314/119264608-31f4da80-bbe4-11eb-8943-fcb3a23c75b7.png)

**Comment by Chew** [comment] 2021-12-30 20:28
Duplicate of https://github.com/mcMMO-Dev/mcMMO/issues/4502#issuecomment-825871597

Thanks for reporting!

**Closed by Chew** 2021-12-30 20:28 UTC
