### ISSUE TITLE
Recent error.

### ISSUE THREAD

**Issue by LogGits** [mcMMO-Dev/mcMMO#3358] opened 2017-12-20 11:21 UTC
Any ideas on this (im running latest build of paperspigot):
```
[mcMMO] Enabling mcMMO v1.5.09-SNAPSHOT
[mcMMO] Killing orphans
WARN 20/12/2017 21:19:36
21:19:36java.lang.Throwable: Warning: A plugin is creating a recipe using a Deprecated method. This will cause you to receive warnings stating 'Tried to load unrecognized recipe: bukkit:<ID>'. Please ask the author to give their recipe a static key using NamespacedKey.
at org.bukkit.inventory.ShapelessRecipe.<init>(ShapelessRecipe.java:26)
at com.gmail.nossr50.util.ChimaeraWing.getChimaeraWingRecipe(ChimaeraWing.java:164)
at com.gmail.nossr50.mcMMO.registerCustomRecipes(mcMMO.java:437)
at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:167)
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:384)
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:333)
at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:226)
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
at java.lang.Thread.run(Thread.java:748)
```

**Comment by benkillin** [comment] 2018-04-04 00:10
I am also experiencing this issue. This is my console output: https://pastebin.com/4CCxyVMh

1.12.2 paperspigot.

**Comment by Glitchfinder** [comment] 2018-04-04 00:40
Duplicate of #3411 and #3416.

**Closed by Glitchfinder** 2018-04-04 00:40 UTC
Labels: Confirmed Bug, Duplicate, Fixed
