### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by TaskTUA0921** [mcMMO-Dev/mcMMO#4723] opened 2022-01-14 11:16 UTC
[19:40:01 ERROR]: [mcMMO] There was an error while enabling mcMMO!
[19:40:01 WARN]: java.lang.NoSuchMethodError: 'org.bukkit.configuration.file.YamlConfigurationOptions org.bukkit.configuration.file.YamlConfigurationOptions.parseComments(boolean)'
[19:40:01 WARN]:        at com.gmail.nossr50.config.BukkitConfig.initConfig(BukkitConfig.java:63)
[19:40:01 WARN]:        at com.gmail.nossr50.config.BukkitConfig.<init>(BukkitConfig.java:27)
[19:40:01 WARN]:        at com.gmail.nossr50.config.GeneralConfig.<init>(GeneralConfig.java:24)
[19:40:01 WARN]:        at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:166)
[19:40:01 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[19:40:01 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[19:40:01 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[19:40:01 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
[19:40:01 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
[19:40:01 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594)
[19:40:01 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298)
[19:40:01 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069)
[19:40:01 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[19:40:01 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[19:40:01 INFO]: [mcMMO] Disabling mcMMO v2.1.208
[19:40:01 INFO]: [mcMMO] Server shutdown has been executed, saving and cleaning up data...
[19:40:01 ERROR]: Error occurred while disabling mcMMO v2.1.208 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:361) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.5.jar:git-Paper-745]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:405) ~[patched_1.16.5.jar:git-Paper-745]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:533) ~[patched_1.16.5.jar:git-Paper-745]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:525) ~[patched_1.16.5.jar:git-Paper-745]
        at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:293) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-745]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-745]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-745]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-745]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-745]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594) ~[patched_1.16.5.jar:git-Paper-745]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-745]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069) ~[patched_1.16.5.jar:git-Paper-745]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-745]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "com.gmail.nossr50.config.AdvancedConfig.getCatalysisMaxBonusLevel()" because the return value of "com.gmail.nossr50.mcMMO.getAdvancedConfig()" is null
        at com.gmail.nossr50.skills.alchemy.Alchemy.<clinit>(Alchemy.java:49) ~[?:?]
        ... 16 more

**Comment by TheBusyBiscuit** [comment] 2022-01-14 12:06
Duplicate of #4716 
Don't worry, it has already been fixed and a new build for it will be released very soon!

**Closed** 2022-01-14 19:26 UTC
Labels: Duplicate
