### ISSUE TITLE
v1.5.01-SNAPSHOT-b3575 -update-> #3677 - clear : flatfile/mcmmo.users

### ISSUE THREAD

**Issue by minecraft7net** [mcMMO-Dev/mcMMO#2229] opened 2014-08-24 01:16 UTC
Hi,

today trying update from v1.5.01-SNAPSHOT-b3575 to #3677.
#3677 clear my user database. flatfile/mcmmo.users

there is any special upgrade procedure ?

i can try convery my flat file to MySQL if it helps (?)

anyway files restored from backup, but please help me with update :)

**Comment by TfT-02** [comment] 2015-01-10 11:37
This ticket is a duplicate of https://github.com/mcMMO-Dev/mcMMO/issues/2225, please refer to that ticket and post your findings or questions on there. We're aware of this issue and are working on a fix.

**Closed by TfT-02** 2015-01-10 11:37 UTC
