### ISSUE TITLE
Dupe glitch, latest version

### ISSUE THREAD

**Issue by Asura35** [mcMMO-Dev/mcMMO#2440] opened 2015-01-30 21:27 UTC
Hey, there is a dupe glitch for all ores that needs to be fixed. I have video proof of this and the events that allow this, it currently works on all servers. Please pm me and I will show you the video. Posting the video here would get it more well known.

**Comment by TfT-02** [comment] 2015-02-09 08:22
Duplicate of https://github.com/mcMMO-Dev/mcMMO/issues/2419

**Closed by TfT-02** 2015-02-09 08:22 UTC
