### ISSUE TITLE
People's skills are being reset when they level up

### ISSUE THREAD

**Issue by ZeTaurin** [mcMMO-Dev/mcMMO#2401] opened 2015-01-07 15:36 UTC
```
[16:29:29 WARN]: [mcMMO] Task #5 for mcMMO v1.5.02-SNAPSHOT-b22 generated an exception java.lang.NullPointerException
        at com.gmail.nossr50.party.PartyManager.saveParties(PartyManager.java:574) ~[?:?]
        at com.gmail.nossr50.runnables.SaveTimerTask.run(SaveTimerTask.java:22)~[?:?]
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-13716d9-0899683]
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-13716d9-0899683]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:694) [spigot.jar:git-Spigot-13716d9-0899683]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-13716d9-0899683]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot.jar:git-Spigot-13716d9-0899683]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot.jar:git-Spigot-13716d9-0899683]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]
```

**Comment by ZeTaurin** [comment] 2015-01-07 15:45
I just now found out that peoples skills are being reset when they level up in that skill, one guy went from 200 to 4 in Archery when they leveled up.

**Comment by ZeTaurin** [comment] 2015-01-07 15:50
Yeah, peoples skills are definitly being reset when they level up.

**Comment by ZeTaurin** [comment] 2015-01-07 16:00
The skills are going backwards.... They are degrading.

**Comment by ZeTaurin** [comment] 2015-01-07 16:14
I think it might be something wrong with Hardcore, people lose skills every 10 minutes without even dying.

**Comment by TfT-02** [comment] 2015-01-10 11:38
This ticket is a duplicate of https://github.com/mcMMO-Dev/mcMMO/issues/2225, please refer to that ticket and post your findings or questions on there. We're aware of this issue and are working on a fix.

**Closed by TfT-02** 2015-01-10 11:38 UTC
