### ISSUE TITLE
Records seem to drop too frequently.

### ISSUE THREAD

**Issue by CollinHerber** [mcMMO-Dev/mcMMO#3383] opened 2018-01-22 17:41 UTC
I am using the latest mcmmo version, and have the stock configuration for treasure on fishing.

They seem to drop at a much higher rate than what is specified.

I am seeing drop rates roughly around 1-5% rather than the specified 0.01%

Notes: 
Minecraft version 1.12.2 on Spigot
Using Rod with Luck of the Sea III, Lure III, Unbreaking III, Mending

Maybe luck of the sea is making this happen? Stock minecraft related?

**Comment by ezeiger92** [comment] 2018-02-16 00:10
Looks like 3% for lure 3
FishingManager.java:
```Java
double diceRoll = Misc.getRandom().nextDouble() * 100;
diceRoll -= getPlayer().getInventory().getItemInMainHand().getEnchantmentLevel(Enchantment.LUCK);
```
Using luck 3, instead of a random number between 0 and 100, diceRoll gets between -3 and 97. Even drops with a 0% chance are picked 3% of the time.

**Comment by CollinHerber** [comment] 2018-02-16 00:13
With vanilla drop table override enabled, this should be classified as a bug then.

**Comment by CollinHerber** [comment] 2018-02-16 00:14
actually, judging by your PR. And my limited view on mobile looks like you addressed this. Am i correct in assuming this?

**Comment by ezeiger92** [comment] 2018-02-16 00:16
Yep, should be fixed in the PR. I just posted on here to describe the cause of the issue for anyone curious.

**Comment by CollinHerber** [comment] 2018-02-16 00:19
I don't suppose you're able to produce a JAR for 1.12 huh? My development computer is currently setup for .NET development and deployment and I've had issues in the past mixing in Java.

**Closed** 2018-02-16 04:00 UTC
