### ISSUE TITLE
Java 17 issue

### ISSUE THREAD

**Issue by JHarris12345** [mcMMO-Dev/mcMMO#4684] opened 2021-12-13 17:47 UTC
Hey, I believe it is wrong for fixing all the memory leaks and forcing people to use java 17 in order to use them. Many plugins do not work properly on java 17 yet (like deluxemenus) and so now I find myself having to delete McMMO for the forseeable future until the other plugins (which take priority) support java 17 properly. Please consider compiling on java 16 so the majority of 1.17 servers can use it

**Comment by broken1arrow** [comment] 2021-12-16 14:45
I agree. Is to soon do dump java 16.

**Comment by CheesyTheArtist** [comment] 2021-12-16 15:26
![image](https://user-images.githubusercontent.com/69735314/146399504-efcbc6a7-da98-41ba-8e20-ba1e1d6d1cd3.png)

**Comment by omaemae** [comment] 2021-12-16 15:44
> mcMMO will target the newest version of MC moving forward, **any backwards compatibility with prior versions of Minecraft should be considered a side effect rather than intended.**

moving forward, there is the possibility that mcMMO will stop working entirely on versions <1.18, so Java 16 support should be the least of your concerns. since the update is fairly recent, we can assume that it may partially work on a 1.17 server running on Java 17. if a plugin doesn't behave as intended under Java 17, you should urge the developers to test, fix, or even contribute if you are able to, so that the specific plugin would work under Java 17 and, therefore, MC 1.18

**however**, other plugins should *not* be considered in this repository as this repository is specific to mcMMO. if you have issues with Java 17 with other plugins, go to **their** issue pages, go to **their** support on Discord or whatever, not here. this repo isn't for that. if i were a maintainer of this repository, i would have closed this issue as it is invalid as the switch to Java 17 is clearly intentional.

**Comment by broken1arrow** [comment] 2021-12-16 15:59
> > mcMMO will target the newest version of MC moving forward, **any backwards compatibility with prior versions of Minecraft should be considered a side effect rather than intended.**
> 
> moving forward, there is the possibility that mcMMO will stop working entirely on versions <1.18, so Java 16 support should be the least of your concerns. since the update is fairly recent, we can assume that it may partially work on a 1.17 server running on Java 17. if a plugin doesn't behave as intended under Java 17, you should urge the developers to test, fix, or even contribute if you are able to, so that the specific plugin would work under Java 17 and, therefore, MC 1.18
> 
> **however**, other plugins should _not_ be considered in this repository as this repository is specific to mcMMO. if you have issues with Java 17 with other plugins, go to **their** issue pages, go to **their** support on Discord or whatever, not here. this repo isn't for that. if i were a maintainer of this repository, i would have closed this issue as it is invalid as the switch to Java 17 is clearly intentional.

You can compile for java 11 and it will run on 1.18. I know he some made deluxe menu are little slow solve bugs (some bugs has been in years). 

But I understand he wants update fast as possible, because 16 have no long term support. But I think want after the holiday (christmas) will not hurt this plugin ether (like other plugins works on 16, should even mcmmo work).  

Now I have to try update to 17 and all problems with some older servers not run (because to new java).

**Comment by omaemae** [comment] 2021-12-19 20:39
> You can compile for java 11 and it will run on 1.18.

that wasn't my point, in fact i already knew this - Java is backwards-compatible, so while a 1.8 server will run on Java 17, a 1.18 server won't run on anything below 1.17.

> Now I have to try update to 17 and all problems with some older servers not run (because to new java).

while there are cases of Java updates breaking compatibility between versions (especially between Java 8 as it's quite old now), it shouldn't impact most plugins.

**Comment by nossr50** [comment] 2021-12-21 01:17
Java 16 will be supported on the next patch, but this won't be a long term goal. Once enough players have migrated to 1.18 ( and thus Java 17 ) we will also migrate mcMMO there too.

**Closed** 2021-12-21 01:17 UTC
