### ISSUE TITLE
wont enable / extremely slow enable times. (since changing to aikar jvm options)

### ISSUE THREAD

**Issue by spidertyler2005** [mcMMO-Dev/mcMMO#4715] opened 2022-01-09 03:23 UTC
I changed my JVM arguments to follow the recommended from the `/timings report` website. these are the "aikar" options.

Ever since I have done this, mcmmo either wont load or will takes 10+ minutes to load. I was wondering why this would happen? 

server info:
```yaml
server-software: purpur (latest)
game-version: 1.18.1
Mcmmo-version: compiled from master (1/8/2022).
xms: 4G
xmx: 4G
```

exact jvm args:
```bash
java -Xms4G -Xmx4G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:InitiatingHeapOccupancyPercent=15 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -jar paper.jar nogui
```

**Comment by Aeon2927** [comment] 2022-01-09 08:57
I have noticed slowing down too and after some days mcmmo starts to fail launching with java.lang.OutOfMemoryError: Java heap space
and a lot of errors after this one

**Comment by TheBusyBiscuit** [comment] 2022-01-09 12:20
Please post your `latest.log` via pastebin or similar.
By looking at the timestamps in the log, one can maybe figure out the cause for this.
Also have a look for your config files and try to see if any of them are particularly large in size.

**Comment by Aeon2927** [comment] 2022-01-09 13:08
Here paper log https://pastebin.com/Qja3jCk7
Here Spigot log https://pastebin.com/YPqFyqTB
experience.yml 96mb! A lot of replications of commented rows. Here https://drive.google.com/file/d/1Q0NKsofThjSga1wR7YcJVTZfWOIMqfgW/view?usp=sharing

**Comment by TheBusyBiscuit** [comment] 2022-01-09 13:17
Yeah, as I suspected. Same issue as #4702.
Make sure you use the latest version of Paper, try to remove all comments from your `experience.yml` file and wait for the comment duplication issue to get fixed.
Then it should work fine.

**Comment by Chew** [comment] 2022-01-09 15:34
Closing as a duplicate then. We're workin on a fix, sorry!

**Closed by Chew** 2022-01-09 15:34 UTC

**Comment by spidertyler2005** [comment] 2022-01-09 15:39
Literally fixed it by closing the screen and opening a new one. I don't know why I didn't try that first.
