### ISSUE TITLE
McMMO keeps Disabling itself?

### ISSUE THREAD

**Issue by XxJRushxX** [mcMMO-Dev/mcMMO#3489] opened 2018-07-10 22:54 UTC
Hi I'm having an issue with McMMO Spigot Version, and it keeps disabling itself for a reason that's unknown to me. Please help!

`[INFO] [mcMMO] Enabling mcMMO v1.5.10-SNAPSHOT

[INFO] [mcMMO] HealthBar plugin found, mcMMO's healthbars are automatically disabled.

[ERROR] [mcMMO] There was an error while enabling mcMMO!

[WARNING] java.lang.IllegalArgumentException: key

[WARNING] at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)

[WARNING] at org.bukkit.NamespacedKey.<init>(NamespacedKey.java:72)

[WARNING] at com.gmail.nossr50.util.ChimaeraWing.getChimaeraWingRecipe(ChimaeraWing.java:161)

[WARNING] at com.gmail.nossr50.mcMMO.registerCustomRecipes(mcMMO.java:437)

[WARNING] at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:167)

[WARNING] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)

[WARNING] at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)

[WARNING] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)

[WARNING] at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381)

[WARNING] at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330)

[WARNING] at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:206)

[WARNING] at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)

[WARNING] at java.lang.Thread.run(Thread.java:748)

[INFO] [mcMMO] Disabling mcMMO v1.5.10-SNAPSHOT`

**Comment by XxJRushxX** [comment] 2018-07-10 22:55
`[INFO] [mcMMO] Enabling mcMMO v1.5.10-SNAPSHOT

[INFO] [mcMMO] HealthBar plugin found, mcMMO's healthbars are automatically disabled.

[ERROR] [mcMMO] There was an error while enabling mcMMO!

[WARNING] java.lang.IllegalArgumentException: key

[WARNING] at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)

[WARNING] at org.bukkit.NamespacedKey.<init>(NamespacedKey.java:72)

[WARNING] at com.gmail.nossr50.util.ChimaeraWing.getChimaeraWingRecipe(ChimaeraWing.java:161)

[WARNING] at com.gmail.nossr50.mcMMO.registerCustomRecipes(mcMMO.java:437)

[WARNING] at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:167)

[WARNING] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)

[WARNING] at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)

[WARNING] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)

[WARNING] at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381)

[WARNING] at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330)

[WARNING] at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:206)

[WARNING] at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)

[WARNING] at java.lang.Thread.run(Thread.java:748)

[INFO] [mcMMO] Disabling mcMMO v1.5.10-SNAPSHOT`

**Comment by Sckaletz** [comment] 2018-07-11 16:44
It's due to the latest update from Spigot git-Spigot-642f6d2-ca6d2cf (MC: 1.12.2). Go back a few updates and it'll work fine. I'm back at git-Spigot-642f6d2-fbe3046 (MC: 1.12.2) which works fine (it's 4 versions old).

**Comment by Coolred303** [comment] 2018-07-12 00:59
Having the same issue. How can I downgrade my Spigot version using BuildTools?

**Comment by ThisTNTSquid** [comment] 2018-07-12 07:35
you can download specific spigot build version jar from Yives Mirror (a site which mirrors various server software jars)

**Comment by LuaTenshi** [comment] 2018-07-12 23:17
So MCMMO and some other plugins currently aren't updated enough to work with the latest version of Spigot?

```
[23:11:14 INFO]: [mcMMO] Enabling mcMMO v1.5.10-SNAPSHOT
[23:11:15 INFO]: [mcMMO] Killing orphans
[23:11:15 ERROR]: [mcMMO] There was an error while enabling mcMMO!
[23:11:15 WARN]: java.lang.IllegalArgumentException: key
[23:11:15 WARN]:        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
[23:11:15 WARN]:        at org.bukkit.NamespacedKey.<init>(NamespacedKey.java:72)
[23:11:15 WARN]:        at com.gmail.nossr50.util.ChimaeraWing.getChimaeraWingRecipe(ChimaeraWing.java:161)
[23:11:15 WARN]:        at com.gmail.nossr50.mcMMO.registerCustomRecipes(mcMMO.java:437)
[23:11:15 WARN]:        at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:167)
[23:11:15 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[23:11:15 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[23:11:15 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[23:11:15 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381)
[23:11:15 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330)
[23:11:15 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:206)
[23:11:15 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
[23:11:15 WARN]:        at java.lang.Thread.run(Thread.java:748)
[23:11:15 INFO]: [mcMMO] Disabling mcMMO v1.5.10-SNAPSHOT
```

Specifically it looks like an error having to do with creating/getting recipes.

**Comment by MarcinWieczorek** [comment] 2018-07-24 13:45
I can confirm.

**Comment by LuaTenshi** [comment] 2018-07-24 13:48
This was fixed a while ago in the latest 1.12.2 build for Spigot.

**Comment by MarcinWieczorek** [comment] 2018-07-24 13:55
Thanks, I'll rebuild and test.

**Comment by t00thpick1** [comment] 2018-07-24 23:30
Closing due to 1.13 overhaul changes in progress touching the affected areas.

**Closed by t00thpick1** 2018-07-24 23:30 UTC
