### ISSUE TITLE
Brewing not consuming potions

### ISSUE THREAD

**Issue by oroJefe** [mcMMO-Dev/mcMMO#3065] opened 2016-11-27 16:48 UTC
Noticed this today on our server, and consulting the logs it seems to be mcMMO related.  After brewing completes, the ingredients are not consumed, and remain in the brewing stand.  Here's the error log:

http://pastebin.com/7SZJRjuu

Using Paper build 937 with plugins: world guard, world edit, core protect, protocol lib, trophy heads, slack, essentials x, dynmap, automessage, mcmmo, creative gates/massive core, pex.

**Comment by FatherWh0** [comment] 2016-11-29 00:02
Not only are the ingredients and blaze powder 'fuel' not consumed but mcmmo xp is not accumulated either. I tried regenerating the potions.yml with no results. I then tried removing the mcmmo folder entirely letting it regen all it's files and flat file database but the errors remained. 
http://pastebin.com/eTmnBYaB
mcmmo 1.5.06
paper 1.11-937
I tested again with spigot, git-Spigot-f950f8e-1c07d5c, rather than paper but with the same results.

**Comment by TheBentoBox** [comment] 2016-11-29 02:23
I've managed to fix this, but of course I'm not a dev here so I can't create a release, nor do I really have the rights to distribute a jar even if it fixes a few issues.

If anyone has the capabilities to do so, you must clone the repo, then go into `src/main/java/com.gmail.nossr50/skills/alchemy/AlchemyPotionBrewer.java` and change lin 131 to say `FakeBrewEvent event = new FakeBrewEvent(brewingStand.getBlock(), inventory, ((BrewingStand) brewingStand).getFuelLevel());`. Then, go into `src/main/java/com.gmail.nossr50/events/fake/FakeBrewEvent.java` and make it look like this (can just copy paste it):

```
package com.gmail.nossr50.events.fake;

import org.bukkit.block.Block;
import org.bukkit.event.inventory.BrewEvent;
import org.bukkit.inventory.BrewerInventory;

public class FakeBrewEvent extends BrewEvent {
    public FakeBrewEvent(Block brewer, BrewerInventory contents, int fuelLevel) {
        super(brewer, contents, fuelLevel);
    }
}
```

That should be all, then you can just build the jar and run it.

The issue is that the Spigot `BrewEvent` was recently updated (literally 2 days ago) to require a `fuelLevel` in the constructor. These changes seem to resolve it -- I'm able to properly brew potions again, including custom mcMMO alchemy ones, and gain alchemy experience from doing so.

I may make a pull request resolving these issues if I can figure out how.

**Comment by TheBentoBox** [comment] 2016-11-29 02:36
[I've created the PR](https://github.com/mcMMO-Dev/mcMMO/pull/3067). If you would like to bypass having to make these changes yourself, my fork is available [here](https://github.com/TheBentoBox/mcMMO), with these changes commited. You can build from that instead to get a jar with working Alchemy on 1.11. I compiled in IntelliJ IDEA using Maven.

**Comment by oroJefe** [comment] 2016-11-29 22:56
That's awesome TheBetoBox :) I realise you aren't one of the devs, do you know if mcMMO is still an active project overall?

**Closed** 2016-12-01 05:55 UTC
