### ISSUE TITLE
Build failure issue with latest version of repo

### ISSUE THREAD

**Issue by cheggisnear** [mcMMO-Dev/mcMMO#4969] opened 2024-02-11 13:47 UTC
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /Users/person/Desktop/development.nosync/mcMMO/src/main/java/com/gmail/nossr50/events/fake/FakeEntityDamageByEntityEvent.java:[12,9] no suitable constructor found for EntityDamageByEntityEvent(@org.jetbrains.annotations.NotNull org.bukkit.entity.Entity,@org.jetbrains.annotations.NotNull org.bukkit.entity.Entity,@org.jetbrains.annotations.NotNull org.bukkit.event.entity.EntityDamageEvent.DamageCause,double)
    constructor org.bukkit.event.entity.EntityDamageByEntityEvent.EntityDamageByEntityEvent(org.bukkit.entity.Entity,org.bukkit.entity.Entity,org.bukkit.event.entity.EntityDamageEvent.DamageCause,org.bukkit.damage.DamageSource,double) is not applicable
      (actual and formal argument lists differ in length)
    constructor org.bukkit.event.entity.EntityDamageByEntityEvent.EntityDamageByEntityEvent(org.bukkit.entity.Entity,org.bukkit.entity.Entity,org.bukkit.event.entity.EntityDamageEvent.DamageCause,org.bukkit.damage.DamageSource,java.util.Map<org.bukkit.event.entity.EntityDamageEvent.DamageModifier,java.lang.Double>,java.util.Map<org.bukkit.event.entity.EntityDamageEvent.DamageModifier,? extends com.google.common.base.Function<? super java.lang.Double,java.lang.Double>>) is not applicable
      (actual and formal argument lists differ in length)
[ERROR] /Users/person/Desktop/development.nosync/mcMMO/src/main/java/com/gmail/nossr50/events/skills/rupture/McMMOEntityDamageByRuptureEvent.java:[12,17] no suitable constructor found for EntityDamageByEntityEvent(org.bukkit.entity.Player,@org.jetbrains.annotations.NotNull org.bukkit.entity.Entity,org.bukkit.event.entity.EntityDamageEvent.DamageCause,double)
    constructor org.bukkit.event.entity.EntityDamageByEntityEvent.EntityDamageByEntityEvent(org.bukkit.entity.Entity,org.bukkit.entity.Entity,org.bukkit.event.entity.EntityDamageEvent.DamageCause,org.bukkit.damage.DamageSource,double) is not applicable
      (actual and formal argument lists differ in length)
    constructor org.bukkit.event.entity.EntityDamageByEntityEvent.EntityDamageByEntityEvent(org.bukkit.entity.Entity,org.bukkit.entity.Entity,org.bukkit.event.entity.EntityDamageEvent.DamageCause,org.bukkit.damage.DamageSource,java.util.Map<org.bukkit.event.entity.EntityDamageEvent.DamageModifier,java.lang.Double>,java.util.Map<org.bukkit.event.entity.EntityDamageEvent.DamageModifier,? extends com.google.common.base.Function<? super java.lang.Double,java.lang.Double>>) is not applicable
      (actual and formal argument lists differ in length)
[ERROR] /Users/person/Desktop/development.nosync/mcMMO/src/main/java/com/gmail/nossr50/events/fake/FakeEntityDamageEvent.java:[12,9] no suitable constructor found for EntityDamageEvent(org.bukkit.entity.Entity,org.bukkit.event.entity.EntityDamageEvent.DamageCause,double)
    constructor org.bukkit.event.entity.EntityDamageEvent.EntityDamageEvent(org.bukkit.entity.Entity,org.bukkit.event.entity.EntityDamageEvent.DamageCause,org.bukkit.damage.DamageSource,double) is not applicable
      (actual and formal argument lists differ in length)
    constructor org.bukkit.event.entity.EntityDamageEvent.EntityDamageEvent(org.bukkit.entity.Entity,org.bukkit.event.entity.EntityDamageEvent.DamageCause,org.bukkit.damage.DamageSource,java.util.Map<org.bukkit.event.entity.EntityDamageEvent.DamageModifier,java.lang.Double>,java.util.Map<org.bukkit.event.entity.EntityDamageEvent.DamageModifier,? extends com.google.common.base.Function<? super java.lang.Double,java.lang.Double>>) is not applicable
      (actual and formal argument lists differ in length)
[INFO] 3 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.446 s
[INFO] Finished at: 2024-02-11T05:34:37-08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project mcMMO: Compilation failure: Compilation failure:
[ERROR] /Users/person/Desktop/development.nosync/mcMMO/src/main/java/com/gmail/nossr50/events/fake/FakeEntityDamageByEntityEvent.java:[12,9] no suitable constructor found for EntityDamageByEntityEvent(@org.jetbrains.annotations.NotNull org.bukkit.entity.Entity,@org.jetbrains.annotations.NotNull org.bukkit.entity.Entity,@org.jetbrains.annotations.NotNull org.bukkit.event.entity.EntityDamageEvent.DamageCause,double)
[ERROR]     constructor org.bukkit.event.entity.EntityDamageByEntityEvent.EntityDamageByEntityEvent(org.bukkit.entity.Entity,org.bukkit.entity.Entity,org.bukkit.event.entity.EntityDamageEvent.DamageCause,org.bukkit.damage.DamageSource,double) is not applicable
[ERROR]       (actual and formal argument lists differ in length)
[ERROR]     constructor org.bukkit.event.entity.EntityDamageByEntityEvent.EntityDamageByEntityEvent(org.bukkit.entity.Entity,org.bukkit.entity.Entity,org.bukkit.event.entity.EntityDamageEvent.DamageCause,org.bukkit.damage.DamageSource,java.util.Map<org.bukkit.event.entity.EntityDamageEvent.DamageModifier,java.lang.Double>,java.util.Map<org.bukkit.event.entity.EntityDamageEvent.DamageModifier,? extends com.google.common.base.Function<? super java.lang.Double,java.lang.Double>>) is not applicable
[ERROR]       (actual and formal argument lists differ in length)
[ERROR] /Users/person/Desktop/development.nosync/mcMMO/src/main/java/com/gmail/nossr50/events/skills/rupture/McMMOEntityDamageByRuptureEvent.java:[12,17] no suitable constructor found for EntityDamageByEntityEvent(org.bukkit.entity.Player,@org.jetbrains.annotations.NotNull org.bukkit.entity.Entity,org.bukkit.event.entity.EntityDamageEvent.DamageCause,double)
[ERROR]     constructor org.bukkit.event.entity.EntityDamageByEntityEvent.EntityDamageByEntityEvent(org.bukkit.entity.Entity,org.bukkit.entity.Entity,org.bukkit.event.entity.EntityDamageEvent.DamageCause,org.bukkit.damage.DamageSource,double) is not applicable
[ERROR]       (actual and formal argument lists differ in length)
[ERROR]     constructor org.bukkit.event.entity.EntityDamageByEntityEvent.EntityDamageByEntityEvent(org.bukkit.entity.Entity,org.bukkit.entity.Entity,org.bukkit.event.entity.EntityDamageEvent.DamageCause,org.bukkit.damage.DamageSource,java.util.Map<org.bukkit.event.entity.EntityDamageEvent.DamageModifier,java.lang.Double>,java.util.Map<org.bukkit.event.entity.EntityDamageEvent.DamageModifier,? extends com.google.common.base.Function<? super java.lang.Double,java.lang.Double>>) is not applicable
[ERROR]       (actual and formal argument lists differ in length)
[ERROR] /Users/person/Desktop/development.nosync/mcMMO/src/main/java/com/gmail/nossr50/events/fake/FakeEntityDamageEvent.java:[12,9] no suitable constructor found for EntityDamageEvent(org.bukkit.entity.Entity,org.bukkit.event.entity.EntityDamageEvent.DamageCause,double)
[ERROR]     constructor org.bukkit.event.entity.EntityDamageEvent.EntityDamageEvent(org.bukkit.entity.Entity,org.bukkit.event.entity.EntityDamageEvent.DamageCause,org.bukkit.damage.DamageSource,double) is not applicable
[ERROR]       (actual and formal argument lists differ in length)
[ERROR]     constructor org.bukkit.event.entity.EntityDamageEvent.EntityDamageEvent(org.bukkit.entity.Entity,org.bukkit.event.entity.EntityDamageEvent.DamageCause,org.bukkit.damage.DamageSource,java.util.Map<org.bukkit.event.entity.EntityDamageEvent.DamageModifier,java.lang.Double>,java.util.Map<org.bukkit.event.entity.EntityDamageEvent.DamageModifier,? extends com.google.common.base.Function<? super java.lang.Double,java.lang.Double>>) is not applicable
[ERROR]       (actual and formal argument lists differ in length)
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

What's going on here?

**Comment by SrBedrock** [comment] 2024-02-12 12:25
Duplicate of #4968

**Closed** 2024-02-12 18:24 UTC
