### ISSUE TITLE
Abilities starting and ending not showing above hotbar

### ISSUE THREAD

**Issue by LukeSmith5853** [mcMMO-Dev/mcMMO#4681] opened 2021-12-08 04:18 UTC
Since putting 2.1.205 onto the 1.18 server, the abilities no longer show above the hotbar / health.
Superbreaker activated and ended is the one I noticed,

**Comment by hamcoremusic** [comment] 2021-12-09 23:23
This seems to be an issue with any action bar message from MCMMO at the moment on my 1.18 server as well (Paper-1.18-build64)

**Comment by nossr50** [comment] 2021-12-10 00:26
I'll see if I can get it fixed in dev soon

**Comment by TDWilkinson99** [comment] 2021-12-10 17:12
Also reproduced on my end (Paper-1.18.1 build 68), for the time being I've enabled "SendCopyOfMessageToChat" for all ActionBarNotifications in the advanced.yml configuration, which as the name suggests, sends a copy of the action bar messages to the standard text chat output.

**Closed** 2021-12-12 06:28 UTC
