### ISSUE TITLE
Duplicate enry for "user" database

### ISSUE THREAD

**Issue by FabioZumbi12** [mcMMO-Dev/mcMMO#2369] opened 2014-12-10 08:34 UTC
I have downloaded the latest dev build and all my database was converted to UUID without errors, but when a players loging on server, cant load their profile because this error:

[06:31:31 ERROR]: [mcMMO] Location: sun.reflect.NativeConstructorAccessorImpl ne
wInstance0 -2
[06:31:31 ERROR]: [mcMMO] SQLException: Duplicate entry 'FabioZumbi12' for key '
user'
[06:31:31 ERROR]: [mcMMO] SQLState: 23000
[06:31:31 ERROR]: [mcMMO] VendorError: 1062

But NOT is duplicated, i have checked!

**Comment by TfT-02** [comment] 2015-01-10 11:39
This ticket is a duplicate of #2349, please refer to that ticket and post your findings or questions on there.

**Closed by TfT-02** 2015-01-10 11:39 UTC
