### ISSUE TITLE
Could not pass event BrewEvent to mcMMO v2.1.202 Spam

### ISSUE THREAD

**Issue by TenkyuChimata** [mcMMO-Dev/mcMMO#4648] opened 2021-11-08 13:10 UTC
https://paste.ubuntu.com/p/nZVzTWptWG/

**Comment by Erlpil** [comment] 2021-11-08 16:42
Duplicate of [https://github.com/mcMMO-Dev/mcMMO/issues/4645](https://github.com/mcMMO-Dev/mcMMO/issues/4645)

**Comment by nossr50** [comment] 2021-11-09 03:34
Fixed

**Closed by nossr50** 2021-11-09 03:34 UTC
