### ISSUE TITLE
1.12.1 version does not use a piston to push the slime blocks

### ISSUE THREAD

**Issue by NyanMeow** [mcMMO-Dev/mcMMO#3256] opened 2017-08-11 12:17 UTC
Hello, because of the recent feedback from the players, my pistons were unable to push the slime blocks. After I checked all the plugins, I found the problem caused by mcMMO. I hope to fix it, thanks!

**Comment by AllPlayed** [comment] 2017-08-15 13:05
Hello
This will be fixed with the new 1.12.1 version of MCMMO, just be patient 🙂

**Comment by AllPlayed** [comment] 2017-08-15 13:05
Hello
This will be fixed with the new 1.12.1 version of MCMMO, just be patient 🙂

**Comment by ezeiger92** [comment] 2017-08-15 21:27
Be skeptical of @AllPlayed, I have not seen a single piece of evidence that he has any affiliation with this project. If I'm wrong, I'll gladly modify my posts. Yes, posts, because I'm copying this everywhere that he copied his post.

**Comment by t00thpick1** [comment] 2017-08-31 04:04
@ezeiger92 Yeah who the heck is that guy ._.

**Comment by t00thpick1** [comment] 2017-09-01 03:56
Unable to reproduce running spigot 1.12.1 and mcMMo current source.

**Closed by t00thpick1** 2017-09-01 03:56 UTC
