### ISSUE TITLE
[BUG] Error every time a player joins

### ISSUE THREAD

**Issue by steveb05** [mcMMO-Dev/mcMMO#4511] opened 2021-05-03 15:32 UTC
**Description:**
Every time a player enters mcMMO gives an error in the console.

**To reproduce:**
Clean server with only mcMMO and the latest version available from Spigot of ViaVersion.

**Additional Context:**
We have updated to the latest version of mcMMO to solve some performance issues that were fixed, however now every time a player enters mcMMO it gives an error in the console. We currently run Yatopia, but I've also tried Paper and Spigot and the problem still occurs.

**Version of mcMMO:** 2.1.196
**Version of ViaVersion:** 3.2.1

**Error Log:**
```
[17:25:48] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to mcMMO v2.1.196
java.lang.NoSuchMethodError: us.myles.ViaVersion.api.ViaAPI.getServerVersion()Lus/myles/ViaVersion/api/protocol/ServerProtocolVersion;
        at com.gmail.nossr50.mcmmo.kyori.adventure.platform.viaversion.ViaFacet.isApplicable(ViaFacet.java:91) ~[?:?]
        at com.gmail.nossr50.mcmmo.kyori.adventure.platform.facet.Facet.of(Facet.java:100) ~[?:?]
        at com.gmail.nossr50.mcmmo.kyori.adventure.platform.facet.FacetAudience.<init>(FacetAudience.java:104) ~[?:?]
        at com.gmail.nossr50.mcmmo.kyori.adventure.platform.bukkit.BukkitAudience.<init>(BukkitAudience.java:85) ~[?:?]
        at com.gmail.nossr50.mcmmo.kyori.adventure.platform.bukkit.BukkitAudiencesImpl.createAudience(BukkitAudiencesImpl.java:162) ~[?:?]
        at com.gmail.nossr50.mcmmo.kyori.adventure.platform.bukkit.BukkitAudiencesImpl.createAudience(BukkitAudiencesImpl.java:71) ~[?:?]
        at com.gmail.nossr50.mcmmo.kyori.adventure.platform.facet.FacetAudienceProvider.lambda$addViewer$0(FacetAudienceProvider.java:89) ~[?:?]
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) ~[?:1.8.0_261]
        at com.gmail.nossr50.mcmmo.kyori.adventure.platform.facet.FacetAudienceProvider.addViewer(FacetAudienceProvider.java:88) ~[?:?]
        at com.gmail.nossr50.mcmmo.kyori.adventure.platform.bukkit.BukkitAudiencesImpl.lambda$new$3(BukkitAudiencesImpl.java:101) ~[?:?]
        at com.gmail.nossr50.mcmmo.kyori.adventure.platform.bukkit.BukkitAudiencesImpl.lambda$registerEvent$5(BukkitAudiencesImpl.java:215) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[TestServer.jar:2991-Spigot-018b9a0-f3f3094]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[TestServer.jar:2991-Spigot-018b9a0-f3f3094]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[TestServer.jar:2991-Spigot-018b9a0-f3f3094]
        at net.minecraft.server.v1_16_R3.PlayerList.a(PlayerList.java:200) ~[TestServer.jar:2991-Spigot-018b9a0-f3f3094]
        at net.minecraft.server.v1_16_R3.LoginListener.c(LoginListener.java:154) ~[TestServer.jar:2991-Spigot-018b9a0-f3f3094]
        at net.minecraft.server.v1_16_R3.LoginListener.tick(LoginListener.java:53) ~[TestServer.jar:2991-Spigot-018b9a0-f3f3094]
        at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:219) ~[TestServer.jar:2991-Spigot-018b9a0-f3f3094]
        at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:130) ~[TestServer.jar:2991-Spigot-018b9a0-f3f3094]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1127) ~[TestServer.jar:2991-Spigot-018b9a0-f3f3094]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:355) ~[TestServer.jar:2991-Spigot-018b9a0-f3f3094]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1008) ~[TestServer.jar:2991-Spigot-018b9a0-f3f3094]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:847) ~[TestServer.jar:2991-Spigot-018b9a0-f3f3094]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[TestServer.jar:2991-Spigot-018b9a0-f3f3094]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_261]
```

**Comment by TheBusyBiscuit** [comment] 2021-05-03 15:34
Duplicate of #4502.

Also make sure to update ViaVersion, they recommend to use their latest dev build.

**Closed** 2021-05-03 15:56 UTC
