### ISSUE TITLE
Piston Ore Duplication bug still exist in  v1.5.02-SNAPSHOT-b27

### ISSUE THREAD

**Issue by jessefjxm** [mcMMO-Dev/mcMMO#2452] opened 2015-02-08 02:36 UTC
Using latest version of spigot & mcmmo (v1.5.02-SNAPSHOT-b27) ,and found that Sticky Piston Ore Duplication bug still exist, which should already been fixed :(

Detail:

Edit:
Test that mcMMO 1.5.00 has already fixed this bug.

**Comment by TfT-02** [comment] 2015-02-09 08:22
Duplicate of https://github.com/mcMMO-Dev/mcMMO/issues/2419

**Closed by TfT-02** 2015-02-09 08:22 UTC

**Comment by k3ldon** [comment] 2015-02-23 21:30
still works =/ on last build
